import { getDatabase, Task } from '@/lib/db'
import { config } from '@/lib/config'
import fs from 'node:fs'
import path from 'node:path'
import { logger } from '@/lib/logger'

export async function syncTaskboardMd() {
  try {
    const workspaceDir = config.openclawHome ? path.join(config.openclawHome, 'workspace') : ''
    if (!workspaceDir) return
    
    // Create workspace dir if it doesn't exist just in case
    if (!fs.existsSync(workspaceDir)) {
      fs.mkdirSync(workspaceDir, { recursive: true })
    }

    const db = getDatabase()
    
    // Get all tasks, excluding done ones that are older than maybe 7 days if we want to keep it clean,
    // but for now let's just get all active tasks. Let's group them by status.
    const tasks = db.prepare(`
      SELECT * FROM tasks 
      WHERE status != 'done' OR (status = 'done' AND completed_at > (unixepoch() - 86400 * 7))
      ORDER BY priority DESC, created_at DESC
    `).all() as Task[]

    const grouped: Record<string, Task[]> = {
      inbox: [],
      assigned: [],
      in_progress: [],
      review: [],
      quality_review: [],
      done: []
    }

    for (const task of tasks) {
      if (grouped[task.status]) {
        grouped[task.status].push(task)
      } else {
        grouped.inbox.push(task) // Fallback
      }
    }

    const priorityEmoji: Record<string, string> = {
      urgent: '🚨',
      high: '🔴',
      medium: '🟡',
      low: '🟢'
    }

    let md = '# 📋 Mission Control Task Board\n\n'
    md += '> *Auto-generated from Mission Control. Do not edit this file manually if you want changes to persist in the UI.*\n\n'

    const renderTask = (t: Task) => {
      const p = priorityEmoji[t.priority] || '⚪'
      const assignee = t.assigned_to ? ` (@${t.assigned_to})` : ''
      let tags = ''
      if (t.tags) {
        try {
          const parsed = JSON.parse(t.tags as string)
          if (Array.isArray(parsed) && parsed.length > 0) {
            tags = ` \`[${parsed.join(', ')}]\``
          }
        } catch (e) {}
      }
      return `- [${t.status === 'done' ? 'x' : ' '}] **MC-${t.id}**: ${t.title} ${p}${assignee}${tags}\n` + 
             (t.description ? `  > ${t.description.split('\\n')[0].substring(0, 100)}${t.description.length > 100 ? '...' : ''}\n` : '')
    }

    md += '## 🚀 In Progress\n'
    if (grouped.in_progress.length === 0) md += '*No tasks in progress.*\n'
    grouped.in_progress.forEach(t => md += renderTask(t))
    md += '\n'

    md += '## 📥 Inbox / To Do\n'
    if (grouped.inbox.length === 0 && grouped.assigned.length === 0) md += '*Inbox is empty.*\n'
    grouped.assigned.forEach(t => md += renderTask(t))
    grouped.inbox.forEach(t => md += renderTask(t))
    md += '\n'

    md += '## 👀 Review\n'
    if (grouped.review.length === 0 && grouped.quality_review.length === 0) md += '*No tasks in review.*\n'
    grouped.review.forEach(t => md += renderTask(t))
    grouped.quality_review.forEach(t => md += renderTask(t))
    md += '\n'

    md += '## ✅ Recently Done (Last 7 Days)\n'
    if (grouped.done.length === 0) md += '*No recent completed tasks.*\n'
    grouped.done.forEach(t => md += renderTask(t))
    md += '\n'

    const targetFile = path.join(workspaceDir, 'mc-tasks.md')
    fs.writeFileSync(targetFile, md, 'utf-8')
    logger.info(`Synced ${tasks.length} tasks to taskboard.md`)
  } catch (error) {
    logger.error({ err: error }, 'Failed to sync taskboard.md')
  }
}
