export { OverviewTab } from './agent-detail/overview-tab'
export { SoulTab } from './agent-detail/soul-tab'
export { MemoryTab } from './agent-detail/memory-tab'
export { TasksTab } from './agent-detail/tasks-tab'
export { ActivityTab } from './agent-detail/activity-tab'
export { ConfigTab } from './agent-detail/config-tab'
export { CreateAgentModal } from './agent-detail/create-agent-modal'
