'use client'

import { useState, useTransition, useEffect, useRef } from 'react'
import type { ApprovalQueueItem, RejectionCategory } from '@/lib/jk/approval-queue'

const GATE_LABELS: Record<number, string> = {
  1: 'Strategi Bulanan',
  2: 'CEP Selection',
  3: 'Content Brief',
  4: 'Content Execution',
}

const REJECTION_CATEGORIES: { value: RejectionCategory; label: string }[] = [
  { value: 'wrong_format', label: 'Format salah' },
  { value: 'wrong_direction', label: 'Arah salah' },
  { value: 'data_error', label: 'Data error' },
  { value: 'other', label: 'Lainnya' },
]

interface Props {
  item: ApprovalQueueItem & { brand_name?: string }
  onDecision?: () => void
}

export function ApprovalCard({ item, onDecision }: Props) {
  const [expanded, setExpanded] = useState(false)
  const [mode, setMode] = useState<'idle' | 'adjust' | 'reject'>('idle')
  const [adjustText, setAdjustText] = useState('')
  const [rejectReason, setRejectReason] = useState('')
  const [rejectCategory, setRejectCategory] = useState<RejectionCategory>('other')
  const [isPending, startTransition] = useTransition()
  const [hovered, setHovered] = useState(false)
  const cardRef = useRef<HTMLDivElement>(null)

  // Y → approve, N → reject — active when card is hovered and idle
  useEffect(() => {
    if (!hovered || mode !== 'idle' || isPending) return
    const handler = (e: KeyboardEvent) => {
      // Don't fire when user is typing in an input
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement || e.target instanceof HTMLSelectElement) return
      if (e.key === 'y' || e.key === 'Y') { e.preventDefault(); handleApprove() }
      if (e.key === 'n' || e.key === 'N') { e.preventDefault(); setMode('reject') }
    }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [hovered, mode, isPending])

  const fullOutput = tryParse(item.full_output)
  const supportingData = tryParse(item.supporting_data)

  async function handleApprove() {
    startTransition(async () => {
      await fetch(`/api/jk/approval/${item.id}/approve`, { method: 'POST' })
      onDecision?.()
    })
  }

  async function handleAdjust() {
    if (!adjustText.trim()) return
    startTransition(async () => {
      await fetch(`/api/jk/approval/${item.id}/adjust`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ adjustment_text: adjustText }),
      })
      setMode('idle')
      setAdjustText('')
      onDecision?.()
    })
  }

  async function handleReject() {
    if (!rejectReason.trim()) return
    startTransition(async () => {
      await fetch(`/api/jk/approval/${item.id}/reject`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ rejection_reason: rejectReason, rejection_category: rejectCategory }),
      })
      setMode('idle')
      setRejectReason('')
      onDecision?.()
    })
  }

  return (
    <div
      ref={cardRef}
      className={`border rounded-lg bg-neutral-900 overflow-hidden transition-colors ${hovered ? 'border-neutral-500' : 'border-neutral-700'}`}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      {/* Header */}
      <div className="px-4 pt-4 pb-3 border-b border-neutral-800">
        <div className="flex items-center gap-2 mb-1">
          <span className="text-xs font-semibold px-2 py-0.5 rounded-full bg-blue-500/20 text-blue-300 border border-blue-500/30">
            Gate {item.gate_number} — {GATE_LABELS[item.gate_number] ?? item.gate_type}
          </span>
          {item.brand_name && (
            <span className="text-xs text-neutral-400">{item.brand_name} | {item.month_year}</span>
          )}
        </div>
        {item.agent_id && (
          <div className="text-xs text-neutral-500">
            Generated by {item.agent_id} — {formatRelativeTime(item.generated_at)}
          </div>
        )}
      </div>

      {/* Recommendation summary */}
      <div className="px-4 py-3">
        <div className="text-xs font-semibold text-neutral-400 uppercase tracking-wider mb-2">Rekomendasi</div>
        <p className="text-sm text-neutral-200 leading-relaxed">{item.summary_text}</p>
      </div>

      {/* Preview content from full_output */}
      {fullOutput && Array.isArray(fullOutput.ideas) && (
        <div className="px-4 pb-3">
          <div className="text-xs font-semibold text-neutral-400 uppercase tracking-wider mb-2">Preview Ide Konten</div>
          <ul className="space-y-1">
            {(fullOutput.ideas as string[]).map((idea: string, i: number) => (
              <li key={i} className="text-sm text-neutral-300 flex gap-2">
                <span className="text-neutral-500 flex-shrink-0">{i + 1}.</span>
                <span>{idea}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Data Pendukung (expandable) */}
      {supportingData && (
        <div className="px-4 pb-3">
          <button
            onClick={() => setExpanded(v => !v)}
            className="text-xs text-blue-400 hover:text-blue-300 flex items-center gap-1"
          >
            <span>{expanded ? '▼' : '▶'}</span>
            Data Pendukung {expanded ? '(tutup)' : '(klik untuk expand)'}
          </button>
          {expanded && (
            <div className="mt-2 bg-neutral-800 rounded p-3 text-xs text-neutral-300 whitespace-pre-wrap font-mono max-h-64 overflow-y-auto">
              {JSON.stringify(supportingData, null, 2)}
            </div>
          )}
        </div>
      )}

      {/* Divider */}
      <div className="border-t border-neutral-800" />

      {/* Adjust form */}
      {mode === 'adjust' && (
        <div className="px-4 py-3 bg-neutral-800/50">
          <textarea
            className="w-full bg-neutral-900 border border-neutral-600 rounded px-3 py-2 text-sm text-neutral-200 placeholder-neutral-500 resize-none focus:outline-none focus:border-blue-500"
            rows={3}
            placeholder="Tulis adjustment di sini — agent akan revisi berdasarkan ini..."
            value={adjustText}
            onChange={e => setAdjustText(e.target.value)}
            autoFocus
          />
          <div className="flex gap-2 mt-2">
            <button
              onClick={handleAdjust}
              disabled={isPending || !adjustText.trim()}
              className="text-xs px-3 py-1.5 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white rounded"
            >
              {isPending ? 'Menyimpan...' : 'Simpan & Trigger Revisi'}
            </button>
            <button onClick={() => setMode('idle')} className="text-xs px-3 py-1.5 text-neutral-400 hover:text-neutral-200">
              Batal
            </button>
          </div>
        </div>
      )}

      {/* Reject form */}
      {mode === 'reject' && (
        <div className="px-4 py-3 bg-neutral-800/50">
          <select
            className="w-full bg-neutral-900 border border-neutral-600 rounded px-3 py-2 text-sm text-neutral-200 mb-2"
            value={rejectCategory}
            onChange={e => setRejectCategory(e.target.value as RejectionCategory)}
          >
            {REJECTION_CATEGORIES.map(c => (
              <option key={c.value} value={c.value}>{c.label}</option>
            ))}
          </select>
          <textarea
            className="w-full bg-neutral-900 border border-neutral-600 rounded px-3 py-2 text-sm text-neutral-200 placeholder-neutral-500 resize-none focus:outline-none focus:border-red-500"
            rows={2}
            placeholder="Alasan reject..."
            value={rejectReason}
            onChange={e => setRejectReason(e.target.value)}
            autoFocus
          />
          <div className="flex gap-2 mt-2">
            <button
              onClick={handleReject}
              disabled={isPending || !rejectReason.trim()}
              className="text-xs px-3 py-1.5 bg-red-600 hover:bg-red-500 disabled:opacity-50 text-white rounded"
            >
              {isPending ? 'Menyimpan...' : 'Kirim Reject'}
            </button>
            <button onClick={() => setMode('idle')} className="text-xs px-3 py-1.5 text-neutral-400 hover:text-neutral-200">
              Batal
            </button>
          </div>
        </div>
      )}

      {/* Action buttons */}
      {mode === 'idle' && (
        <div className="px-4 py-3 flex flex-wrap gap-2 items-center">
          <button
            onClick={handleApprove}
            disabled={isPending}
            className="flex items-center gap-1.5 text-sm px-4 py-2 bg-green-700 hover:bg-green-600 disabled:opacity-50 text-white rounded font-medium"
          >
            ✓ Approve{fullOutput?.ideas ? ' Semua' : ''}
            {hovered && <kbd className="ml-1 text-xs opacity-60 font-mono">Y</kbd>}
          </button>
          <button
            onClick={() => setMode('adjust')}
            className="flex items-center gap-1.5 text-sm px-4 py-2 bg-neutral-700 hover:bg-neutral-600 text-neutral-200 rounded"
          >
            ✎ Adjust
          </button>
          <button
            onClick={() => setMode('reject')}
            className="flex items-center gap-1.5 text-sm px-4 py-2 bg-neutral-700 hover:bg-neutral-600 text-neutral-200 rounded"
          >
            ✗ Reject
            {hovered && <kbd className="ml-1 text-xs opacity-60 font-mono">N</kbd>}
          </button>
        </div>
      )}
    </div>
  )
}

function tryParse(json: string | null | undefined): any {
  if (!json) return null
  try { return JSON.parse(json) } catch { return null }
}

function formatRelativeTime(unixTs: number): string {
  const diff = Math.floor(Date.now() / 1000) - unixTs
  if (diff < 60) return 'baru saja'
  if (diff < 3600) return `${Math.floor(diff / 60)} menit lalu`
  if (diff < 86400) return `${Math.floor(diff / 3600)} jam lalu`
  return `${Math.floor(diff / 86400)} hari lalu`
}
