import { getDatabase } from '../db';
import { logger } from '../logger';

export interface DebriefResult {
  sessionId: string;
  projectSlug: string;
  markdown: string;
  stats: {
    totalLoc: number;
    successRate: number;
    estimatedCost: number;
    toolUses: number;
  };
}

/**
 * Service to generate high-fidelity Mission Debriefs (Summaries) 
 * for completed or active agent sessions.
 */
export async function generateMissionDebrief(sessionId: string): Promise<DebriefResult | null> {
  const db = getDatabase();
  
  try {
    const session = db.prepare(`
      SELECT * FROM claude_sessions WHERE session_id = ?
    `).get(sessionId) as any;

    if (!session) return null;

    const toolUses = session.tool_uses || 0;
    const successes = session.tool_success_count || 0;
    const errors = session.tool_error_count || 0;
    const successRate = toolUses > 0 ? Math.round((successes / toolUses) * 100) : 100;

    const locByLang = session.loc_by_language ? JSON.parse(session.loc_by_language) : {};
    const langStats = Object.entries(locByLang)
      .map(([lang, loc]) => `- **${lang}**: ${loc} lines`)
      .join('\n');

    const stabilityRating = session.stability_score >= 0.8 ? 'OPTIMAL' : 
                           session.stability_score >= 0.5 ? 'DEGRADED' : 'CRITICAL';

    const markdown = `
# MISSION DEBRIEF: ${session.project_slug}
## SESSION ID: \`${session.session_id}\`
### STATUS: ${session.is_active ? 'ACTIVE' : 'COMPLETED'}

---

### 1. INTELLIGENCE SUMMARY
- **Material Impact**: ${session.total_loc_delta} net lines of code 
- **Stability Rating**: ${stabilityRating} (${Math.round(session.stability_score * 100)}%)
- **Compute Burden**: $${session.estimated_cost.toFixed(4)}
- **Tool Efficiency**: ${successRate}% success rate across ${toolUses} operations

### 2. LANGUAGE DISTRIBUTION
${langStats || '- No code changes detected.'}

### 3. TACTICAL OUTCOME (LAST INTENT)
> "${session.last_user_prompt || 'No intent captured.'}"

---
*Generated by Aegis Active Intelligence — ${new Date().toISOString()}*
    `.trim();

    return {
      sessionId: session.session_id,
      projectSlug: session.project_slug,
      markdown,
      stats: {
        totalLoc: session.total_loc_delta,
        successRate,
        estimatedCost: session.estimated_cost,
        toolUses
      }
    };
  } catch (err) {
    logger.error({ err, sessionId }, 'Failed to generate mission debrief');
    return null;
  }
}
