import { describe, it, expect, vi, beforeEach } from 'vitest'

// Mock dependencies
vi.mock('better-sqlite3', () => {
  const defaultStmt = {
    run: vi.fn(() => ({ lastInsertRowid: 1, changes: 1 })),
    get: vi.fn(() => null),
    all: vi.fn(() => []),
  }
  const mockPrepare = vi.fn(() => ({ ...defaultStmt }))
  const mockDb = {
    pragma: vi.fn(),
    prepare: mockPrepare,
    exec: vi.fn(),
    close: vi.fn(),
    transaction: vi.fn((fn: Function) => fn),
  }
  return { default: vi.fn(() => mockDb) }
})

vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))
vi.mock('@/lib/migrations', () => ({ runMigrations: vi.fn() }))
vi.mock('@/lib/phase-migrations', () => ({}))

// Mock getDatabase to avoid real DB initialization in executeAutonomousAction
const mockGetDb = {
  prepare: vi.fn(() => ({
    get: vi.fn(() => undefined),
    all: vi.fn(() => []),
    run: vi.fn(() => ({ lastInsertRowid: 1, changes: 1 })),
  })),
}
vi.mock('@/lib/db', () => ({
  getDatabase: vi.fn(() => mockGetDb),
  writeTransaction: vi.fn((_db: unknown, fn: Function) => fn(_db)),
}))
vi.mock('@/lib/event-bus', () => ({
  eventBus: { broadcast: vi.fn(), on: vi.fn(), off: vi.fn() },
}))
vi.mock('@/lib/password', () => ({ hashPassword: vi.fn(() => 'hash') }))
vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn(), debug: vi.fn() },
}))
vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))
vi.mock('@/lib/llm/router', () => ({
  complete: vi.fn(async () => ({ text: 'test response', tokenCount: { input: 5, output: 5 }, cost: 0.001, latencyMs: 100, model: 'test' })),
  checkAgentBudget: vi.fn(() => ({ allowed: true, spent: 0, limit: 100 })),
}))
vi.mock('@/lib/persona-engine', () => ({
  buildSystemPrompt: vi.fn(() => 'You are a test agent.'),
  getMentalState: vi.fn(() => ({})),
  updateMentalState: vi.fn(),
}))
vi.mock('@/lib/agent-memory', () => ({
  recall: vi.fn(() => []),
  observe: vi.fn(async () => 1),
}))
vi.mock('@/lib/debate-engine', () => ({
  submitArgument: vi.fn(() => ({ id: 1, budgetRemaining: 1000 })),
  castVote: vi.fn(() => ({ allVoted: false, accept: 1, reject: 0 })),
  getDebateStatus: vi.fn(() => ({
    debate: { id: 1, topic: 'test', status: 'propose', current_round: 1 },
    participants: [],
    arguments: [],
    votes: [],
  })),
  advanceDebatePhase: vi.fn(() => ({ status: 'critique', round: 1 })),
}))
vi.mock('@/lib/workflow-engine', () => ({
  completePhase: vi.fn(() => ({ status: 'completed' })),
  advanceWorkflow: vi.fn(() => ({ status: 'running', nextPhase: { id: 2, name: 'Phase 2', requiresApproval: false } })),
}))

describe('agent-actions', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  const mockAgent = {
    id: 1,
    name: 'Alice',
    role: 'worker',
    soul_content: null,
    config: null,
    workspace_id: 1,
  }

  describe('checkPendingMentions', () => {
    it('returns null when no pending mentions', async () => {
      const { checkPendingMentions } = await import('@/lib/agent-actions')

      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => undefined),
        })),
      } as any

      const result = checkPendingMentions(mockDb, 1, 'Alice', 1)
      expect(result).toBeNull()
    })

    it('returns pending mention when found', async () => {
      const { checkPendingMentions } = await import('@/lib/agent-actions')

      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => ({
            id: 42,
            conversation_id: 'conv-1',
            content: 'hey @alice check this',
            from_agent: 'Bob',
          })),
        })),
      } as any

      const result = checkPendingMentions(mockDb, 1, 'Alice', 1)
      expect(result).toEqual({
        type: 'mention_response',
        messageId: 42,
        conversationId: 'conv-1',
        content: 'hey @alice check this',
        fromAgent: 'Bob',
      })
    })

    it('normalizes agent handle for LIKE query', async () => {
      const { checkPendingMentions } = await import('@/lib/agent-actions')

      const prepareSpy = vi.fn(() => ({ get: vi.fn(() => undefined) }))
      const mockDb = { prepare: prepareSpy } as any

      checkPendingMentions(mockDb, 1, 'Alice Smith', 1)
      expect(prepareSpy).toHaveBeenCalled()
      // The LIKE pattern should use normalized handle
      const getSpy = prepareSpy.mock.results[0].value.get
      const args = getSpy.mock.calls[0]
      // Second arg should be the LIKE pattern with normalized handle
      expect(args[1]).toBe('%@alice-smith%')
    })
  })

  describe('checkPendingWorkflowPhases', () => {
    it('returns null when no running phases', async () => {
      const { checkPendingWorkflowPhases } = await import('@/lib/agent-actions')

      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => undefined),
        })),
      } as any

      const result = checkPendingWorkflowPhases(mockDb, 'worker', 1)
      expect(result).toBeNull()
    })

    it('returns running phase matching agent role', async () => {
      const { checkPendingWorkflowPhases } = await import('@/lib/agent-actions')

      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => ({
            phaseRunId: 5,
            runId: 10,
            input_artifact: '{"spec": "build widget"}',
            phaseName: 'Implementation',
            output_schema: '{"required": ["code"]}',
            description: 'Write the code',
          })),
        })),
      } as any

      const result = checkPendingWorkflowPhases(mockDb, 'engineer', 1)
      expect(result).toEqual({
        type: 'workflow_phase',
        runId: 10,
        phaseRunId: 5,
        phaseName: 'Implementation',
        inputArtifact: '{"spec": "build widget"}',
        outputSchema: '{"required": ["code"]}',
        description: 'Write the code',
      })
    })
  })

  describe('checkPendingDebateTurns', () => {
    it('returns null when no active debates', async () => {
      const { checkPendingDebateTurns } = await import('@/lib/agent-actions')

      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => undefined),
        })),
      } as any

      const result = checkPendingDebateTurns(mockDb, 1, 1)
      expect(result).toBeNull()
    })

    it('returns active debate turn', async () => {
      const { checkPendingDebateTurns } = await import('@/lib/agent-actions')

      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => ({
            debateId: 3,
            topic: 'Should we use microservices?',
            currentPhase: 'propose',
            current_round: 1,
          })),
        })),
      } as any

      const result = checkPendingDebateTurns(mockDb, 1, 1)
      expect(result).toEqual({
        type: 'debate_turn',
        debateId: 3,
        topic: 'Should we use microservices?',
        currentPhase: 'propose',
        currentRound: 1,
        agentId: 1,
      })
    })
  })

  describe('getAgentPrioritizedAction', () => {
    it('returns null when nothing pending', async () => {
      const { getAgentPrioritizedAction } = await import('@/lib/agent-actions')

      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => undefined),
        })),
      } as any

      const result = getAgentPrioritizedAction(mockDb, 1, 'Alice', 'worker', 1)
      expect(result).toBeNull()
    })

    it('prioritizes mentions over workflows', async () => {
      const { getAgentPrioritizedAction } = await import('@/lib/agent-actions')

      let callCount = 0
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => {
            callCount++
            // First call is the mention check — return a pending mention
            if (callCount === 1) {
              return {
                id: 42,
                conversation_id: 'conv-1',
                content: 'hey @alice',
                from_agent: 'Bob',
              }
            }
            return undefined
          }),
        })),
      } as any

      const result = getAgentPrioritizedAction(mockDb, 1, 'Alice', 'worker', 1)
      expect(result).not.toBeNull()
      expect(result!.type).toBe('mention_response')
      expect(result!.priority).toBe(1)
    })

    it('falls through to workflow when no mentions', async () => {
      const { getAgentPrioritizedAction } = await import('@/lib/agent-actions')

      let callCount = 0
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => {
            callCount++
            // First call is mention check — none
            if (callCount === 1) return undefined
            // Second call is workflow check — found
            if (callCount === 2) {
              return {
                phaseRunId: 5,
                runId: 10,
                input_artifact: null,
                phaseName: 'Review',
                output_schema: null,
                description: null,
              }
            }
            return undefined
          }),
        })),
      } as any

      const result = getAgentPrioritizedAction(mockDb, 1, 'Alice', 'reviewer', 1)
      expect(result).not.toBeNull()
      expect(result!.type).toBe('workflow_phase')
      expect(result!.priority).toBe(2)
    })

    it('falls through to debate when no mentions or workflows', async () => {
      const { getAgentPrioritizedAction } = await import('@/lib/agent-actions')

      let callCount = 0
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => {
            callCount++
            if (callCount <= 2) return undefined
            if (callCount === 3) {
              return {
                debateId: 7,
                topic: 'API design',
                currentPhase: 'critique',
                current_round: 2,
              }
            }
            return undefined
          }),
        })),
      } as any

      const result = getAgentPrioritizedAction(mockDb, 1, 'Alice', 'worker', 1)
      expect(result).not.toBeNull()
      expect(result!.type).toBe('debate_turn')
      expect(result!.priority).toBe(3)
    })
  })

  describe('respondToMention', () => {
    it('generates LLM response and inserts message', async () => {
      const { respondToMention } = await import('@/lib/agent-actions')
      const { complete } = await import('@/lib/llm/router')
      const { eventBus } = await import('@/lib/event-bus')

      const insertSpy = vi.fn(() => ({ lastInsertRowid: 100, changes: 1 }))
      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('FROM messages') && sql.includes('ORDER BY')) {
            return { all: vi.fn(() => []) }
          }
          if (sql.includes('INSERT INTO messages')) {
            return { run: insertSpy }
          }
          return { get: vi.fn(), all: vi.fn(() => []), run: vi.fn() }
        }),
      } as any

      await respondToMention(mockDb, mockAgent, {
        type: 'mention_response',
        messageId: 42,
        conversationId: 'conv-1',
        content: 'hey @alice what do you think?',
        fromAgent: 'Bob',
      })

      expect(complete).toHaveBeenCalled()
      expect(insertSpy).toHaveBeenCalled()
      expect(eventBus.broadcast).toHaveBeenCalledWith('chat.mention.response', {
        messageId: 42,
        agentName: 'Alice',
        conversationId: 'conv-1',
      })
    })

    it('skips response when agent turn limit reached', async () => {
      const { respondToMention } = await import('@/lib/agent-actions')
      const { complete } = await import('@/lib/llm/router')

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('FROM messages') && sql.includes('ORDER BY')) {
            // 3 consecutive agent messages — at the limit
            return {
              all: vi.fn(() => [
                { from_agent: 'Agent1' },
                { from_agent: 'Agent2' },
                { from_agent: 'Agent3' },
              ]),
            }
          }
          return { get: vi.fn(), all: vi.fn(() => []), run: vi.fn() }
        }),
      } as any

      await respondToMention(mockDb, mockAgent, {
        type: 'mention_response',
        messageId: 42,
        conversationId: 'conv-1',
        content: 'hey @alice',
        fromAgent: 'Bob',
      })

      expect(complete).not.toHaveBeenCalled()
    })

    it('posts fallback message when LLM times out (CHAT-04)', async () => {
      const { respondToMention } = await import('@/lib/agent-actions')
      const { complete } = await import('@/lib/llm/router')
      const { logger } = await import('@/lib/logger')

      // Make LLM hang for 10s (longer than 5s timeout)
      vi.mocked(complete).mockImplementationOnce(
        () => new Promise((resolve) => setTimeout(resolve, 10_000)) as any
      )

      const insertSpy = vi.fn(() => ({ lastInsertRowid: 100, changes: 1 }))
      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('FROM messages') && sql.includes('ORDER BY')) {
            return { all: vi.fn(() => []) }
          }
          if (sql.includes('INSERT INTO messages')) {
            return { run: insertSpy }
          }
          return { get: vi.fn(), all: vi.fn(() => []), run: vi.fn() }
        }),
      } as any

      await respondToMention(mockDb, mockAgent, {
        type: 'mention_response',
        messageId: 42,
        conversationId: 'conv-1',
        content: 'hey @alice',
        fromAgent: 'Bob',
      })

      // Should still insert a message (the fallback)
      expect(insertSpy).toHaveBeenCalled()
      const insertArgs = insertSpy.mock.calls[0] as unknown[]
      expect(insertArgs[2]).toContain("get back to you")
      expect(logger.warn).toHaveBeenCalledWith(
        expect.objectContaining({ agentId: 1 }),
        expect.stringContaining('timed out')
      )
    }, 10_000) // Allow 10s for this test
  })

  describe('executeWorkflowPhase', () => {
    it('generates output and completes phase', async () => {
      const { executeWorkflowPhase } = await import('@/lib/agent-actions')
      const { complete } = await import('@/lib/llm/router')
      const { completePhase, advanceWorkflow } = await import('@/lib/workflow-engine')

      const mockDb = {} as any

      await executeWorkflowPhase(mockDb, mockAgent, {
        type: 'workflow_phase',
        runId: 10,
        phaseRunId: 5,
        phaseName: 'Design',
        inputArtifact: '{"requirement": "build widget"}',
        outputSchema: '{"required": ["design"]}',
        description: 'Create design document',
      })

      expect(complete).toHaveBeenCalled()
      expect(completePhase).toHaveBeenCalledWith(mockDb, 10, 5, 'test response')
      expect(advanceWorkflow).toHaveBeenCalledWith(mockDb, 10)
    })

    it('does not advance when validation fails', async () => {
      const { executeWorkflowPhase } = await import('@/lib/agent-actions')
      const { completePhase, advanceWorkflow } = await import('@/lib/workflow-engine')

      vi.mocked(completePhase).mockReturnValueOnce({
        status: 'validation_error',
        validationError: 'Missing required field: code',
      })

      const mockDb = {} as any

      await executeWorkflowPhase(mockDb, mockAgent, {
        type: 'workflow_phase',
        runId: 10,
        phaseRunId: 5,
        phaseName: 'Implementation',
        inputArtifact: null,
        outputSchema: '{"required": ["code"]}',
        description: null,
      })

      expect(completePhase).toHaveBeenCalled()
      expect(advanceWorkflow).not.toHaveBeenCalled()
    })
  })

  describe('participateInDebate', () => {
    it('submits argument for propose phase', async () => {
      const { participateInDebate } = await import('@/lib/agent-actions')
      const { complete } = await import('@/lib/llm/router')
      const { submitArgument } = await import('@/lib/debate-engine')

      const mockDb = {} as any

      await participateInDebate(mockDb, mockAgent, {
        type: 'debate_turn',
        debateId: 3,
        topic: 'Should we use microservices?',
        currentPhase: 'propose',
        currentRound: 1,
        agentId: 1,
      })

      expect(complete).toHaveBeenCalled()
      expect(submitArgument).toHaveBeenCalledWith(
        mockDb,
        3,
        1,
        'test response',
        expect.any(Number)
      )
    })

    it('casts vote during vote phase', async () => {
      const { participateInDebate } = await import('@/lib/agent-actions')
      const { castVote } = await import('@/lib/debate-engine')
      const { complete } = await import('@/lib/llm/router')

      vi.mocked(complete).mockResolvedValueOnce({
        text: '{"vote": "accept", "reason": "good proposal"}',
        tokenCount: { input: 5, output: 5 },
        cost: 0.001,
        latencyMs: 100,
        model: 'test',
      })

      const mockDb = {} as any

      await participateInDebate(mockDb, mockAgent, {
        type: 'debate_turn',
        debateId: 3,
        topic: 'API design',
        currentPhase: 'vote',
        currentRound: 1,
        agentId: 1,
      })

      expect(castVote).toHaveBeenCalledWith(mockDb, 3, 1, 'accept', 'good proposal')
    })

    it('advances debate when all voted', async () => {
      const { participateInDebate } = await import('@/lib/agent-actions')
      const { castVote, advanceDebatePhase } = await import('@/lib/debate-engine')
      const { complete } = await import('@/lib/llm/router')

      vi.mocked(complete).mockResolvedValueOnce({
        text: '{"vote": "reject", "reason": "too risky"}',
        tokenCount: { input: 5, output: 5 },
        cost: 0.001,
        latencyMs: 100,
        model: 'test',
      })

      vi.mocked(castVote).mockReturnValueOnce({
        allVoted: true,
        accept: 1,
        reject: 2,
      })

      const mockDb = {} as any

      await participateInDebate(mockDb, mockAgent, {
        type: 'debate_turn',
        debateId: 3,
        topic: 'API design',
        currentPhase: 'vote',
        currentRound: 1,
        agentId: 1,
      })

      expect(advanceDebatePhase).toHaveBeenCalledWith(mockDb, 3)
    })
  })

  describe('executeAutonomousAction', () => {
    it('returns false when budget exceeded', async () => {
      const { executeAutonomousAction } = await import('@/lib/agent-actions')
      const { checkAgentBudget } = await import('@/lib/llm/router')

      vi.mocked(checkAgentBudget).mockReturnValueOnce({
        allowed: false,
        spent: 10,
        limit: 10,
      })

      const result = await executeAutonomousAction(mockAgent)
      expect(result).toBe(false)
    })

    it('returns false when no pending actions', async () => {
      const { executeAutonomousAction } = await import('@/lib/agent-actions')

      const result = await executeAutonomousAction(mockAgent)
      expect(result).toBe(false)
    })
  })
})
