import { describe, it, expect, vi, beforeEach } from 'vitest'
import { z } from 'zod'

// Mock better-sqlite3
vi.mock('better-sqlite3', () => {
  const defaultStmt = {
    run: vi.fn(() => ({ lastInsertRowid: 1, changes: 1 })),
    get: vi.fn(() => ({ count: 0 })),
    all: vi.fn(() => []),
  }
  const mockPrepare = vi.fn(() => ({ ...defaultStmt }))
  const mockDb = {
    pragma: vi.fn(),
    prepare: mockPrepare,
    exec: vi.fn(),
    close: vi.fn(),
  }
  return { default: vi.fn(() => mockDb) }
})

vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))
vi.mock('@/lib/migrations', () => ({ runMigrations: vi.fn() }))
vi.mock('@/lib/phase-migrations', () => ({}))
vi.mock('@/lib/event-bus', () => ({
  eventBus: { broadcast: vi.fn(), on: vi.fn(), off: vi.fn() },
}))
vi.mock('@/lib/password', () => ({ hashPassword: vi.fn(() => 'hash') }))
vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}))
vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

// --- Zod Schemas (replicated from routes for validation testing) ---

const createDebateSchema = z.object({
  topic: z.string().min(1).max(1000),
  participantIds: z.array(z.number().int().positive()).min(2).max(20),
  maxRounds: z.number().int().min(1).max(20).default(3),
  tokenBudget: z.number().int().min(100).max(1_000_000).default(10_000),
})

const deleteDebateSchema = z.object({
  id: z.number().int().positive(),
})

const submitArgumentSchema = z.object({
  agentId: z.number().int().positive(),
  content: z.string().min(1).max(50_000),
  confidence: z.number().min(0).max(1),
})

const voteSchema = z.object({
  agentId: z.number().int().positive(),
  vote: z.enum(['accept', 'reject']),
  reason: z.string().max(5000).optional(),
})

const startDebateSchema = z.object({
  topic: z.string().min(1).max(1000),
  participantIds: z.array(z.number().int().positive()).min(2).max(10),
  maxRounds: z.number().int().min(1).max(20).optional(),
  tokenBudget: z.number().int().min(100).max(1_000_000).optional(),
})

// --- Tests ---

describe('createDebateSchema', () => {
  it('accepts valid debate creation with all fields', () => {
    const result = createDebateSchema.safeParse({
      topic: 'Should we use microservices?',
      participantIds: [1, 2, 3],
      maxRounds: 5,
      tokenBudget: 50_000,
    })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.topic).toBe('Should we use microservices?')
      expect(result.data.participantIds).toEqual([1, 2, 3])
      expect(result.data.maxRounds).toBe(5)
      expect(result.data.tokenBudget).toBe(50_000)
    }
  })

  it('applies defaults for maxRounds and tokenBudget', () => {
    const result = createDebateSchema.safeParse({
      topic: 'Test topic',
      participantIds: [1, 2],
    })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.maxRounds).toBe(3)
      expect(result.data.tokenBudget).toBe(10_000)
    }
  })

  it('rejects empty topic', () => {
    const result = createDebateSchema.safeParse({
      topic: '',
      participantIds: [1, 2],
    })
    expect(result.success).toBe(false)
  })

  it('rejects topic exceeding 1000 characters', () => {
    const result = createDebateSchema.safeParse({
      topic: 'x'.repeat(1001),
      participantIds: [1, 2],
    })
    expect(result.success).toBe(false)
  })

  it('rejects fewer than 2 participants', () => {
    const result = createDebateSchema.safeParse({
      topic: 'Test',
      participantIds: [1],
    })
    expect(result.success).toBe(false)
  })

  it('rejects more than 20 participants', () => {
    const ids = Array.from({ length: 21 }, (_, i) => i + 1)
    const result = createDebateSchema.safeParse({
      topic: 'Test',
      participantIds: ids,
    })
    expect(result.success).toBe(false)
  })

  it('rejects non-positive participant IDs', () => {
    const result = createDebateSchema.safeParse({
      topic: 'Test',
      participantIds: [0, 2],
    })
    expect(result.success).toBe(false)
  })

  it('rejects non-integer participant IDs', () => {
    const result = createDebateSchema.safeParse({
      topic: 'Test',
      participantIds: [1.5, 2],
    })
    expect(result.success).toBe(false)
  })

  it('rejects maxRounds exceeding 20', () => {
    const result = createDebateSchema.safeParse({
      topic: 'Test',
      participantIds: [1, 2],
      maxRounds: 21,
    })
    expect(result.success).toBe(false)
  })

  it('rejects maxRounds of 0', () => {
    const result = createDebateSchema.safeParse({
      topic: 'Test',
      participantIds: [1, 2],
      maxRounds: 0,
    })
    expect(result.success).toBe(false)
  })

  it('rejects tokenBudget below 100', () => {
    const result = createDebateSchema.safeParse({
      topic: 'Test',
      participantIds: [1, 2],
      tokenBudget: 50,
    })
    expect(result.success).toBe(false)
  })

  it('rejects tokenBudget exceeding 1,000,000', () => {
    const result = createDebateSchema.safeParse({
      topic: 'Test',
      participantIds: [1, 2],
      tokenBudget: 1_000_001,
    })
    expect(result.success).toBe(false)
  })

  it('rejects missing participantIds', () => {
    const result = createDebateSchema.safeParse({ topic: 'Test' })
    expect(result.success).toBe(false)
  })

  it('accepts exactly 2 participants (minimum)', () => {
    const result = createDebateSchema.safeParse({
      topic: 'Test',
      participantIds: [1, 2],
    })
    expect(result.success).toBe(true)
  })

  it('accepts exactly 20 participants (maximum)', () => {
    const ids = Array.from({ length: 20 }, (_, i) => i + 1)
    const result = createDebateSchema.safeParse({
      topic: 'Test',
      participantIds: ids,
    })
    expect(result.success).toBe(true)
  })
})

describe('deleteDebateSchema', () => {
  it('accepts valid positive integer id', () => {
    const result = deleteDebateSchema.safeParse({ id: 42 })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.id).toBe(42)
    }
  })

  it('rejects zero id', () => {
    const result = deleteDebateSchema.safeParse({ id: 0 })
    expect(result.success).toBe(false)
  })

  it('rejects negative id', () => {
    const result = deleteDebateSchema.safeParse({ id: -1 })
    expect(result.success).toBe(false)
  })

  it('rejects non-integer id', () => {
    const result = deleteDebateSchema.safeParse({ id: 1.5 })
    expect(result.success).toBe(false)
  })

  it('rejects missing id', () => {
    const result = deleteDebateSchema.safeParse({})
    expect(result.success).toBe(false)
  })

  it('rejects string id', () => {
    const result = deleteDebateSchema.safeParse({ id: 'abc' })
    expect(result.success).toBe(false)
  })
})

describe('submitArgumentSchema', () => {
  it('accepts valid argument submission', () => {
    const result = submitArgumentSchema.safeParse({
      agentId: 1,
      content: 'I believe we should adopt this approach because...',
      confidence: 0.85,
    })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.agentId).toBe(1)
      expect(result.data.confidence).toBe(0.85)
    }
  })

  it('rejects empty content', () => {
    const result = submitArgumentSchema.safeParse({
      agentId: 1,
      content: '',
      confidence: 0.5,
    })
    expect(result.success).toBe(false)
  })

  it('rejects content exceeding 50,000 characters', () => {
    const result = submitArgumentSchema.safeParse({
      agentId: 1,
      content: 'x'.repeat(50_001),
      confidence: 0.5,
    })
    expect(result.success).toBe(false)
  })

  it('accepts confidence of 0 (minimum)', () => {
    const result = submitArgumentSchema.safeParse({
      agentId: 1,
      content: 'test',
      confidence: 0,
    })
    expect(result.success).toBe(true)
  })

  it('accepts confidence of 1 (maximum)', () => {
    const result = submitArgumentSchema.safeParse({
      agentId: 1,
      content: 'test',
      confidence: 1,
    })
    expect(result.success).toBe(true)
  })

  it('rejects confidence below 0', () => {
    const result = submitArgumentSchema.safeParse({
      agentId: 1,
      content: 'test',
      confidence: -0.1,
    })
    expect(result.success).toBe(false)
  })

  it('rejects confidence above 1', () => {
    const result = submitArgumentSchema.safeParse({
      agentId: 1,
      content: 'test',
      confidence: 1.1,
    })
    expect(result.success).toBe(false)
  })

  it('rejects non-positive agentId', () => {
    const result = submitArgumentSchema.safeParse({
      agentId: 0,
      content: 'test',
      confidence: 0.5,
    })
    expect(result.success).toBe(false)
  })

  it('rejects missing fields', () => {
    expect(submitArgumentSchema.safeParse({}).success).toBe(false)
    expect(submitArgumentSchema.safeParse({ agentId: 1 }).success).toBe(false)
    expect(submitArgumentSchema.safeParse({ agentId: 1, content: 'x' }).success).toBe(false)
  })
})

describe('voteSchema', () => {
  it('accepts valid accept vote with reason', () => {
    const result = voteSchema.safeParse({
      agentId: 1,
      vote: 'accept',
      reason: 'Strong arguments presented',
    })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.vote).toBe('accept')
      expect(result.data.reason).toBe('Strong arguments presented')
    }
  })

  it('accepts valid reject vote without reason', () => {
    const result = voteSchema.safeParse({
      agentId: 2,
      vote: 'reject',
    })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.vote).toBe('reject')
      expect(result.data.reason).toBeUndefined()
    }
  })

  it('rejects invalid vote value', () => {
    const result = voteSchema.safeParse({
      agentId: 1,
      vote: 'abstain',
    })
    expect(result.success).toBe(false)
  })

  it('rejects missing vote field', () => {
    const result = voteSchema.safeParse({ agentId: 1 })
    expect(result.success).toBe(false)
  })

  it('rejects missing agentId', () => {
    const result = voteSchema.safeParse({ vote: 'accept' })
    expect(result.success).toBe(false)
  })

  it('rejects reason exceeding 5000 characters', () => {
    const result = voteSchema.safeParse({
      agentId: 1,
      vote: 'accept',
      reason: 'x'.repeat(5001),
    })
    expect(result.success).toBe(false)
  })

  it('accepts reason at exactly 5000 characters', () => {
    const result = voteSchema.safeParse({
      agentId: 1,
      vote: 'accept',
      reason: 'x'.repeat(5000),
    })
    expect(result.success).toBe(true)
  })

  it('rejects non-positive agentId', () => {
    const result = voteSchema.safeParse({
      agentId: -1,
      vote: 'accept',
    })
    expect(result.success).toBe(false)
  })
})

describe('startDebateSchema (backward-compat)', () => {
  it('accepts valid start request with all fields', () => {
    const result = startDebateSchema.safeParse({
      topic: 'Architecture decision',
      participantIds: [1, 2, 3],
      maxRounds: 5,
      tokenBudget: 20_000,
    })
    expect(result.success).toBe(true)
  })

  it('accepts start request with only required fields', () => {
    const result = startDebateSchema.safeParse({
      topic: 'Quick debate',
      participantIds: [1, 2],
    })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.maxRounds).toBeUndefined()
      expect(result.data.tokenBudget).toBeUndefined()
    }
  })

  it('max 10 participants for start endpoint', () => {
    const ids = Array.from({ length: 11 }, (_, i) => i + 1)
    const result = startDebateSchema.safeParse({
      topic: 'Test',
      participantIds: ids,
    })
    expect(result.success).toBe(false)
  })

  it('accepts exactly 10 participants', () => {
    const ids = Array.from({ length: 10 }, (_, i) => i + 1)
    const result = startDebateSchema.safeParse({
      topic: 'Test',
      participantIds: ids,
    })
    expect(result.success).toBe(true)
  })
})

describe('debate-engine exports', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('exports createDebate function', async () => {
    const mod = await import('@/lib/debate-engine')
    expect(typeof mod.createDebate).toBe('function')
  })

  it('exports submitArgument function', async () => {
    const mod = await import('@/lib/debate-engine')
    expect(typeof mod.submitArgument).toBe('function')
  })

  it('exports advanceDebatePhase function', async () => {
    const mod = await import('@/lib/debate-engine')
    expect(typeof mod.advanceDebatePhase).toBe('function')
  })

  it('exports castVote function', async () => {
    const mod = await import('@/lib/debate-engine')
    expect(typeof mod.castVote).toBe('function')
  })

  it('exports getDebateStatus function', async () => {
    const mod = await import('@/lib/debate-engine')
    expect(typeof mod.getDebateStatus).toBe('function')
  })

  it('exports concludeDebate function', async () => {
    const mod = await import('@/lib/debate-engine')
    expect(typeof mod.concludeDebate).toBe('function')
  })
})

describe('debate phase advancement validation', () => {
  it('valid debate phases are propose, critique, rebut, vote', () => {
    const validPhases = ['propose', 'critique', 'rebut', 'vote']
    for (const phase of validPhases) {
      expect(typeof phase).toBe('string')
    }
    expect(validPhases).toHaveLength(4)
  })

  it('concluded and budget_exhausted are terminal states', () => {
    const terminalStatuses = ['concluded', 'budget_exhausted']
    // These should not allow further advancement
    for (const status of terminalStatuses) {
      expect(status).toBeTruthy()
    }
  })

  it('vote values are accept or reject only', () => {
    const voteEnum = z.enum(['accept', 'reject'])
    expect(voteEnum.safeParse('accept').success).toBe(true)
    expect(voteEnum.safeParse('reject').success).toBe(true)
    expect(voteEnum.safeParse('abstain').success).toBe(false)
    expect(voteEnum.safeParse('maybe').success).toBe(false)
  })
})

describe('query parameter validation', () => {
  it('status filter values match debate statuses', () => {
    const validStatuses = ['pending', 'propose', 'critique', 'rebut', 'vote', 'concluded', 'budget_exhausted']
    for (const s of validStatuses) {
      expect(typeof s).toBe('string')
      expect(s.length).toBeGreaterThan(0)
    }
  })

  it('pagination defaults are reasonable', () => {
    const defaultLimit = 50
    const maxLimit = 100
    const defaultOffset = 0

    expect(defaultLimit).toBeLessThanOrEqual(maxLimit)
    expect(defaultOffset).toBe(0)
    expect(Math.min(parseInt('200', 10), maxLimit)).toBe(100)
    expect(Math.min(parseInt('50', 10), maxLimit)).toBe(50)
  })

  it('round and phase filters are valid query params for arguments', () => {
    const validRounds = [1, 2, 3, 4, 5]
    const validPhases = ['propose', 'critique', 'rebut']

    for (const r of validRounds) {
      expect(Number.isInteger(r)).toBe(true)
      expect(r).toBeGreaterThan(0)
    }
    for (const p of validPhases) {
      expect(typeof p).toBe('string')
    }
  })
})
