import { describe, it, expect, vi, beforeEach } from 'vitest'

// Mock better-sqlite3
vi.mock('better-sqlite3', () => {
  const defaultStmt = {
    run: vi.fn(() => ({ lastInsertRowid: 1, changes: 1 })),
    get: vi.fn(() => ({ count: 0 })),
    all: vi.fn(() => []),
  }
  const mockPrepare = vi.fn(() => ({ ...defaultStmt }))
  const mockDb = {
    pragma: vi.fn(),
    prepare: mockPrepare,
    exec: vi.fn(),
    close: vi.fn(),
  }
  return { default: vi.fn(() => mockDb) }
})

vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))
vi.mock('@/lib/migrations', () => ({ runMigrations: vi.fn() }))
vi.mock('@/lib/phase-migrations', () => ({}))
vi.mock('@/lib/event-bus', () => ({
  eventBus: { broadcast: vi.fn(), on: vi.fn(), off: vi.fn() },
}))
vi.mock('@/lib/password', () => ({ hashPassword: vi.fn(() => 'hash') }))
vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}))
vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

// Mock writeTransaction to just call the callback
vi.mock('@/lib/db', async (importOriginal) => {
  const orig = await importOriginal<typeof import('@/lib/db')>()
  return {
    ...orig,
    writeTransaction: vi.fn((_db: unknown, fn: (db: unknown) => unknown) => fn(_db)),
    getDatabase: orig.getDatabase,
  }
})

describe('debate-engine', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  describe('module exports', () => {
    it('exports all 6 functions', async () => {
      const mod = await import('@/lib/debate-engine')
      expect(typeof mod.createDebate).toBe('function')
      expect(typeof mod.submitArgument).toBe('function')
      expect(typeof mod.advanceDebatePhase).toBe('function')
      expect(typeof mod.castVote).toBe('function')
      expect(typeof mod.getDebateStatus).toBe('function')
      expect(typeof mod.concludeDebate).toBe('function')
    })

    it('exports type interfaces (compile check)', async () => {
      const mod = await import('@/lib/debate-engine')
      const debateRow: import('@/lib/debate-engine').DebateRow = {
        id: 1, topic: 'Test', status: 'pending', current_round: 1,
        max_rounds: 3, token_budget: 100000, tokens_used: 0,
        outcome: null, vote_accept: 0, vote_reject: 0,
        workspace_id: 1, created_by: 'system', created_at: 0, concluded_at: null,
      }
      const argRow: import('@/lib/debate-engine').DebateArgumentRow = {
        id: 1, debate_id: 1, agent_id: 1, agent_name: 'Agent-1',
        round_number: 1, phase: 'propose', content: 'test',
        confidence: 0.8, tokens_used: 10, created_at: 0,
      }
      const voteRow: import('@/lib/debate-engine').DebateVoteRow = {
        id: 1, debate_id: 1, agent_id: 1, agent_name: 'Agent-1',
        vote: 'accept', reason: null, created_at: 0,
      }
      const participantRow: import('@/lib/debate-engine').DebateParticipantRow = {
        debate_id: 1, agent_id: 1, agent_name: 'Agent-1', joined_at: 0,
      }
      expect(debateRow.status).toBe('pending')
      expect(argRow.phase).toBe('propose')
      expect(voteRow.vote).toBe('accept')
      expect(participantRow.agent_name).toBe('Agent-1')
      expect(mod).toBeDefined()
    })
  })

  describe('createDebate', () => {
    it('throws when fewer than 2 participants', async () => {
      const { createDebate } = await import('@/lib/debate-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          run: vi.fn(() => ({ lastInsertRowid: 1, changes: 1 })),
          get: vi.fn(),
          all: vi.fn(() => []),
        })),
      } as any

      expect(() => createDebate(mockDb, 'Topic', [1], 3, 100000, 'admin', 1))
        .toThrow('Debate requires at least 2 participants')
    })

    it('throws when agent not found in workspace', async () => {
      const { createDebate } = await import('@/lib/debate-engine')
      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('INSERT INTO debates')) {
            return { run: vi.fn(() => ({ lastInsertRowid: BigInt(1), changes: 1 })) }
          }
          if (sql.includes('INSERT INTO debate_participants')) {
            return { run: vi.fn() }
          }
          if (sql.includes('SELECT name FROM agents')) {
            return { get: vi.fn(() => undefined) }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      expect(() => createDebate(mockDb, 'Topic', [1, 2], 3, 100000, 'admin', 1))
        .toThrow('Agent 1 not found in workspace 1')
    })

    it('creates debate with valid participants', async () => {
      const { createDebate } = await import('@/lib/debate-engine')
      const { eventBus } = await import('@/lib/event-bus')

      const insertDebateStmt = vi.fn(() => ({ lastInsertRowid: BigInt(42), changes: 1 }))
      const insertParticipantStmt = vi.fn()
      let agentCallCount = 0

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('INSERT INTO debates')) {
            return { run: insertDebateStmt }
          }
          if (sql.includes('INSERT INTO debate_participants')) {
            return { run: insertParticipantStmt }
          }
          if (sql.includes('SELECT name FROM agents')) {
            return {
              get: vi.fn(() => {
                agentCallCount++
                return { name: `Agent-${agentCallCount}` }
              }),
            }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = createDebate(mockDb, 'Should we deploy?', [10, 20], 3, 50000, 'admin', 1)
      expect(result.debateId).toBe(42)
      expect(insertDebateStmt).toHaveBeenCalledWith('Should we deploy?', 3, 50000, 'admin', 1)
      expect(insertParticipantStmt).toHaveBeenCalledTimes(2)
      expect(eventBus.broadcast).toHaveBeenCalledWith('debate.created', {
        debateId: 42,
        topic: 'Should we deploy?',
        participantCount: 2,
      })
    })
  })

  describe('submitArgument', () => {
    it('throws when debate not found', async () => {
      const { submitArgument } = await import('@/lib/debate-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => undefined),
          run: vi.fn(),
        })),
      } as any

      expect(() => submitArgument(mockDb, 999, 1, 'content', 0.8))
        .toThrow('Debate not found')
    })

    it('throws when debate is not in argument phase', async () => {
      const { submitArgument } = await import('@/lib/debate-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => ({
            id: 1, status: 'vote', current_round: 1,
            token_budget: 100000, tokens_used: 0,
          })),
          run: vi.fn(),
        })),
      } as any

      expect(() => submitArgument(mockDb, 1, 1, 'content', 0.8))
        .toThrow('Cannot submit argument in vote phase')
    })

    it('throws when agent is not a participant', async () => {
      const { submitArgument } = await import('@/lib/debate-engine')
      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates')) {
            return {
              get: vi.fn(() => ({
                id: 1, status: 'propose', current_round: 1,
                token_budget: 100000, tokens_used: 0,
              })),
            }
          }
          if (sql.includes('SELECT agent_name FROM debate_participants')) {
            return { get: vi.fn(() => undefined) }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      expect(() => submitArgument(mockDb, 1, 99, 'content', 0.8))
        .toThrow('Agent is not a participant in this debate')
    })

    it('throws when agent already submitted for round+phase', async () => {
      const { submitArgument } = await import('@/lib/debate-engine')
      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates')) {
            return {
              get: vi.fn(() => ({
                id: 1, status: 'propose', current_round: 1,
                token_budget: 100000, tokens_used: 0,
              })),
            }
          }
          if (sql.includes('SELECT agent_name FROM debate_participants')) {
            return { get: vi.fn(() => ({ agent_name: 'Agent-1' })) }
          }
          if (sql.includes('SELECT id FROM debate_arguments')) {
            return { get: vi.fn(() => ({ id: 5 })) }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      expect(() => submitArgument(mockDb, 1, 1, 'content', 0.8))
        .toThrow('Agent already submitted argument for this round and phase')
    })

    it('exhausts budget and updates status', async () => {
      const { submitArgument } = await import('@/lib/debate-engine')
      const updateStmt = vi.fn()
      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates')) {
            return {
              get: vi.fn(() => ({
                id: 1, status: 'propose', current_round: 1,
                token_budget: 10, tokens_used: 5,
              })),
            }
          }
          if (sql.includes('SELECT agent_name FROM debate_participants')) {
            return { get: vi.fn(() => ({ agent_name: 'Agent-1' })) }
          }
          if (sql.includes('SELECT id FROM debate_arguments')) {
            return { get: vi.fn(() => undefined) }
          }
          if (sql.includes('UPDATE debates SET status')) {
            return { run: updateStmt }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      // Content that exceeds remaining budget (10 - 5 = 5 tokens, but content has > 20 chars)
      expect(() => submitArgument(mockDb, 1, 1, 'This is a long argument that exceeds the budget', 0.8))
        .toThrow('Token budget exhausted')
      expect(updateStmt).toHaveBeenCalledWith('budget_exhausted', 1)
    })

    it('submits argument successfully', async () => {
      const { submitArgument } = await import('@/lib/debate-engine')
      const { eventBus } = await import('@/lib/event-bus')

      const insertStmt = vi.fn(() => ({ lastInsertRowid: BigInt(7), changes: 1 }))
      const updateTokensStmt = vi.fn()

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates')) {
            return {
              get: vi.fn(() => ({
                id: 1, status: 'propose', current_round: 1,
                token_budget: 100000, tokens_used: 0,
              })),
            }
          }
          if (sql.includes('SELECT agent_name FROM debate_participants')) {
            return { get: vi.fn(() => ({ agent_name: 'Agent-1' })) }
          }
          if (sql.includes('SELECT id FROM debate_arguments')) {
            return { get: vi.fn(() => undefined) }
          }
          if (sql.includes('INSERT INTO debate_arguments')) {
            return { run: insertStmt }
          }
          if (sql.includes('UPDATE debates SET tokens_used')) {
            return { run: updateTokensStmt }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = submitArgument(mockDb, 1, 1, 'I propose we proceed', 0.9)
      expect(result.id).toBe(7)
      expect(result.budgetRemaining).toBeGreaterThan(0)
      expect(insertStmt).toHaveBeenCalled()
      expect(updateTokensStmt).toHaveBeenCalled()
      expect(eventBus.broadcast).toHaveBeenCalledWith('debate.argument.submitted', {
        debateId: 1,
        agentName: 'Agent-1',
        roundNumber: 1,
      })
    })
  })

  describe('advanceDebatePhase', () => {
    it('throws when debate not found', async () => {
      const { advanceDebatePhase } = await import('@/lib/debate-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => undefined),
          run: vi.fn(),
          all: vi.fn(() => []),
        })),
      } as any

      expect(() => advanceDebatePhase(mockDb, 999)).toThrow('Debate not found')
    })

    it('throws when debate already concluded', async () => {
      const { advanceDebatePhase } = await import('@/lib/debate-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => ({ id: 1, status: 'concluded', current_round: 1 })),
          run: vi.fn(),
          all: vi.fn(() => []),
        })),
      } as any

      expect(() => advanceDebatePhase(mockDb, 1)).toThrow('Debate already ended: concluded')
    })

    it('throws when debate is budget_exhausted', async () => {
      const { advanceDebatePhase } = await import('@/lib/debate-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => ({ id: 1, status: 'budget_exhausted', current_round: 1 })),
          run: vi.fn(),
          all: vi.fn(() => []),
        })),
      } as any

      expect(() => advanceDebatePhase(mockDb, 1)).toThrow('Debate already ended: budget_exhausted')
    })

    it('advances propose → critique', async () => {
      const { advanceDebatePhase } = await import('@/lib/debate-engine')
      const { eventBus } = await import('@/lib/event-bus')
      const updateStmt = vi.fn()

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates')) {
            return {
              get: vi.fn(() => ({ id: 1, status: 'propose', current_round: 1, max_rounds: 3 })),
            }
          }
          if (sql.includes('UPDATE debates SET status')) {
            return { run: updateStmt }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = advanceDebatePhase(mockDb, 1)
      expect(result.status).toBe('critique')
      expect(result.round).toBe(1)
      expect(updateStmt).toHaveBeenCalledWith('critique', 1)
      expect(eventBus.broadcast).toHaveBeenCalledWith('debate.round.started', {
        debateId: 1, roundNumber: 1, phase: 'critique',
      })
    })

    it('advances critique → rebut', async () => {
      const { advanceDebatePhase } = await import('@/lib/debate-engine')
      const updateStmt = vi.fn()

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates')) {
            return {
              get: vi.fn(() => ({ id: 1, status: 'critique', current_round: 1, max_rounds: 3 })),
            }
          }
          if (sql.includes('UPDATE debates SET status')) {
            return { run: updateStmt }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = advanceDebatePhase(mockDb, 1)
      expect(result.status).toBe('rebut')
      expect(updateStmt).toHaveBeenCalledWith('rebut', 1)
    })

    it('advances rebut → vote', async () => {
      const { advanceDebatePhase } = await import('@/lib/debate-engine')
      const updateStmt = vi.fn()

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates')) {
            return {
              get: vi.fn(() => ({ id: 1, status: 'rebut', current_round: 1, max_rounds: 3 })),
            }
          }
          if (sql.includes('UPDATE debates SET status')) {
            return { run: updateStmt }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = advanceDebatePhase(mockDb, 1)
      expect(result.status).toBe('vote')
      expect(updateStmt).toHaveBeenCalledWith('vote', 1)
    })

    it('concludes with accepted when majority votes accept', async () => {
      const { advanceDebatePhase } = await import('@/lib/debate-engine')
      const { eventBus } = await import('@/lib/event-bus')
      const updateVotesStmt = vi.fn()
      const concludeStmt = vi.fn()

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates')) {
            return {
              get: vi.fn(() => ({
                id: 1, status: 'vote', current_round: 1, max_rounds: 3,
                vote_accept: 0, vote_reject: 0,
              })),
            }
          }
          if (sql.includes('SELECT vote FROM debate_votes')) {
            return {
              all: vi.fn(() => [
                { vote: 'accept' }, { vote: 'accept' }, { vote: 'reject' },
              ]),
            }
          }
          if (sql.includes('UPDATE debates SET vote_accept')) {
            return { run: updateVotesStmt }
          }
          if (sql.includes('UPDATE debates SET status')) {
            return { run: concludeStmt }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = advanceDebatePhase(mockDb, 1)
      expect(result.status).toBe('concluded')
      expect(updateVotesStmt).toHaveBeenCalledWith(2, 1, 1)
      expect(concludeStmt).toHaveBeenCalledWith('concluded', 'accepted', 1)
      expect(eventBus.broadcast).toHaveBeenCalledWith('debate.concluded', {
        debateId: 1, outcome: 'accepted', voteCount: { accept: 2, reject: 1 },
      })
    })

    it('advances to next round when no consensus and rounds remain', async () => {
      const { advanceDebatePhase } = await import('@/lib/debate-engine')
      const { eventBus } = await import('@/lib/event-bus')
      const updateVotesStmt = vi.fn()
      const advanceRoundStmt = vi.fn()
      const deleteVotesStmt = vi.fn()

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates')) {
            return {
              get: vi.fn(() => ({
                id: 1, status: 'vote', current_round: 1, max_rounds: 3,
              })),
            }
          }
          if (sql.includes('SELECT vote FROM debate_votes')) {
            return {
              all: vi.fn(() => [
                { vote: 'reject' }, { vote: 'reject' }, { vote: 'accept' },
              ]),
            }
          }
          if (sql.includes('UPDATE debates SET vote_accept')) {
            return { run: updateVotesStmt }
          }
          if (sql.includes('UPDATE debates SET status = ?, current_round')) {
            return { run: advanceRoundStmt }
          }
          if (sql.includes('DELETE FROM debate_votes')) {
            return { run: deleteVotesStmt }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = advanceDebatePhase(mockDb, 1)
      expect(result.status).toBe('propose')
      expect(result.round).toBe(2)
      expect(advanceRoundStmt).toHaveBeenCalledWith('propose', 2, 1)
      expect(deleteVotesStmt).toHaveBeenCalledWith(1)
      expect(eventBus.broadcast).toHaveBeenCalledWith('debate.round.started', {
        debateId: 1, roundNumber: 2, phase: 'propose',
      })
    })

    it('concludes with no_consensus at max rounds with tie', async () => {
      const { advanceDebatePhase } = await import('@/lib/debate-engine')
      const { eventBus } = await import('@/lib/event-bus')

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates')) {
            return {
              get: vi.fn(() => ({
                id: 1, status: 'vote', current_round: 3, max_rounds: 3,
              })),
            }
          }
          if (sql.includes('SELECT vote FROM debate_votes')) {
            return {
              all: vi.fn(() => [
                { vote: 'accept' }, { vote: 'reject' },
              ]),
            }
          }
          if (sql.includes('UPDATE debates SET vote_accept')) {
            return { run: vi.fn() }
          }
          if (sql.includes('UPDATE debates SET status')) {
            return { run: vi.fn() }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = advanceDebatePhase(mockDb, 1)
      expect(result.status).toBe('concluded')
      expect(eventBus.broadcast).toHaveBeenCalledWith('debate.concluded', {
        debateId: 1, outcome: 'no_consensus', voteCount: { accept: 1, reject: 1 },
      })
    })

    it('concludes with rejected at max rounds with majority reject', async () => {
      const { advanceDebatePhase } = await import('@/lib/debate-engine')
      const { eventBus } = await import('@/lib/event-bus')

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates')) {
            return {
              get: vi.fn(() => ({
                id: 1, status: 'vote', current_round: 3, max_rounds: 3,
              })),
            }
          }
          if (sql.includes('SELECT vote FROM debate_votes')) {
            return {
              all: vi.fn(() => [
                { vote: 'reject' }, { vote: 'reject' }, { vote: 'accept' },
              ]),
            }
          }
          if (sql.includes('UPDATE debates SET vote_accept')) {
            return { run: vi.fn() }
          }
          if (sql.includes('UPDATE debates SET status')) {
            return { run: vi.fn() }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = advanceDebatePhase(mockDb, 1)
      expect(result.status).toBe('concluded')
      expect(eventBus.broadcast).toHaveBeenCalledWith('debate.concluded', {
        debateId: 1, outcome: 'rejected', voteCount: { accept: 1, reject: 2 },
      })
    })
  })

  describe('castVote', () => {
    it('throws when debate not found', async () => {
      const { castVote } = await import('@/lib/debate-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => undefined),
          run: vi.fn(),
          all: vi.fn(() => []),
        })),
      } as any

      expect(() => castVote(mockDb, 999, 1, 'accept')).toThrow('Debate not found')
    })

    it('throws when debate is not in vote phase', async () => {
      const { castVote } = await import('@/lib/debate-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => ({ id: 1, status: 'propose' })),
          run: vi.fn(),
          all: vi.fn(() => []),
        })),
      } as any

      expect(() => castVote(mockDb, 1, 1, 'accept')).toThrow('Debate is not in voting phase')
    })

    it('throws when agent is not a participant', async () => {
      const { castVote } = await import('@/lib/debate-engine')
      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates')) {
            return { get: vi.fn(() => ({ id: 1, status: 'vote' })) }
          }
          if (sql.includes('SELECT agent_name FROM debate_participants')) {
            return { get: vi.fn(() => undefined) }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      expect(() => castVote(mockDb, 1, 99, 'accept')).toThrow('Agent is not a participant')
    })

    it('casts vote successfully and returns tally', async () => {
      const { castVote } = await import('@/lib/debate-engine')
      const { eventBus } = await import('@/lib/event-bus')
      const insertVoteStmt = vi.fn()

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates')) {
            return { get: vi.fn(() => ({ id: 1, status: 'vote' })) }
          }
          if (sql.includes('SELECT agent_name FROM debate_participants')) {
            return { get: vi.fn(() => ({ agent_name: 'Agent-1' })) }
          }
          if (sql.includes('INSERT INTO debate_votes')) {
            return { run: insertVoteStmt }
          }
          if (sql.includes('SELECT COUNT(*)')) {
            return { get: vi.fn(() => ({ count: 2 })) }
          }
          if (sql.includes('SELECT vote FROM debate_votes')) {
            return {
              all: vi.fn(() => [
                { vote: 'accept' }, { vote: 'reject' },
              ]),
            }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = castVote(mockDb, 1, 1, 'accept', 'Good proposal')
      expect(result.allVoted).toBe(true)
      expect(result.accept).toBe(1)
      expect(result.reject).toBe(1)
      expect(insertVoteStmt).toHaveBeenCalledWith(1, 1, 'Agent-1', 'accept', 'Good proposal')
      expect(eventBus.broadcast).toHaveBeenCalledWith('debate.vote.cast', {
        debateId: 1, agentName: 'Agent-1', vote: 'accept',
      })
    })

    it('indicates when not all voted yet', async () => {
      const { castVote } = await import('@/lib/debate-engine')

      let countCallNum = 0
      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates')) {
            return { get: vi.fn(() => ({ id: 1, status: 'vote' })) }
          }
          if (sql.includes('SELECT agent_name FROM debate_participants')) {
            return { get: vi.fn(() => ({ agent_name: 'Agent-1' })) }
          }
          if (sql.includes('INSERT INTO debate_votes')) {
            return { run: vi.fn() }
          }
          if (sql.includes('SELECT COUNT(*)')) {
            countCallNum++
            // First call: participant count (3), second: vote count (1)
            return { get: vi.fn(() => ({ count: countCallNum === 1 ? 3 : 1 })) }
          }
          if (sql.includes('SELECT vote FROM debate_votes')) {
            return { all: vi.fn(() => [{ vote: 'accept' }]) }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = castVote(mockDb, 1, 1, 'accept')
      expect(result.allVoted).toBe(false)
    })
  })

  describe('getDebateStatus', () => {
    it('returns null when debate not found', async () => {
      const { getDebateStatus } = await import('@/lib/debate-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => undefined),
          all: vi.fn(() => []),
        })),
      } as any

      const result = getDebateStatus(mockDb, 999)
      expect(result).toBeNull()
    })

    it('returns full debate status with participants, arguments, votes', async () => {
      const { getDebateStatus } = await import('@/lib/debate-engine')

      const debate = {
        id: 1, topic: 'Topic', status: 'propose', current_round: 1,
        max_rounds: 3, token_budget: 100000, tokens_used: 500,
        outcome: null, vote_accept: 0, vote_reject: 0,
        workspace_id: 1, created_by: 'admin', created_at: 1000, concluded_at: null,
      }
      const participants = [{ debate_id: 1, agent_id: 1, agent_name: 'Agent-1', joined_at: 1000 }]
      const args = [{ id: 1, debate_id: 1, agent_id: 1, agent_name: 'Agent-1', round_number: 1, phase: 'propose', content: 'test', confidence: 0.8, tokens_used: 10, created_at: 1001 }]
      const votes: unknown[] = []

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates WHERE id')) {
            return { get: vi.fn(() => debate) }
          }
          if (sql.includes('SELECT * FROM debate_participants')) {
            return { all: vi.fn(() => participants) }
          }
          if (sql.includes('SELECT * FROM debate_arguments')) {
            return { all: vi.fn(() => args) }
          }
          if (sql.includes('SELECT * FROM debate_votes')) {
            return { all: vi.fn(() => votes) }
          }
          return { get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = getDebateStatus(mockDb, 1)
      expect(result).not.toBeNull()
      expect(result!.debate).toEqual(debate)
      expect(result!.participants).toHaveLength(1)
      expect(result!.arguments).toHaveLength(1)
      expect(result!.votes).toHaveLength(0)
    })
  })

  describe('concludeDebate', () => {
    it('throws when debate not found', async () => {
      const { concludeDebate } = await import('@/lib/debate-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => undefined),
          run: vi.fn(),
          all: vi.fn(() => []),
        })),
      } as any

      expect(() => concludeDebate(mockDb, 999, 'manual')).toThrow('Debate not found')
    })

    it('concludes debate and broadcasts event', async () => {
      const { concludeDebate } = await import('@/lib/debate-engine')
      const { eventBus } = await import('@/lib/event-bus')
      const updateStmt = vi.fn()

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM debates WHERE id')) {
            return {
              get: vi.fn(() => ({ id: 1, status: 'propose', current_round: 1 })),
            }
          }
          if (sql.includes('UPDATE debates SET status')) {
            return { run: updateStmt }
          }
          if (sql.includes('SELECT vote FROM debate_votes')) {
            return { all: vi.fn(() => [{ vote: 'accept' }]) }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      concludeDebate(mockDb, 1, 'manual_override')
      expect(updateStmt).toHaveBeenCalledWith('concluded', 'manual_override', 1)
      expect(eventBus.broadcast).toHaveBeenCalledWith('debate.concluded', {
        debateId: 1, outcome: 'manual_override', voteCount: { accept: 1, reject: 0 },
      })
    })
  })
})
