import { describe, it, expect, vi, beforeEach } from 'vitest'

// Mock better-sqlite3
vi.mock('better-sqlite3', () => {
  const defaultStmt = {
    run: vi.fn(() => ({ lastInsertRowid: 1, changes: 1 })),
    get: vi.fn(() => ({ count: 0 })),
    all: vi.fn(() => []),
  }
  const mockPrepare = vi.fn(() => ({ ...defaultStmt }))
  const mockDb = {
    pragma: vi.fn(),
    prepare: mockPrepare,
    exec: vi.fn(),
    close: vi.fn(),
  }
  return { default: vi.fn(() => mockDb) }
})

vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))
vi.mock('@/lib/migrations', () => ({ runMigrations: vi.fn() }))
vi.mock('@/lib/phase-migrations', () => ({}))
vi.mock('@/lib/event-bus', () => ({
  eventBus: { broadcast: vi.fn(), on: vi.fn(), off: vi.fn() },
}))
vi.mock('@/lib/password', () => ({ hashPassword: vi.fn(() => 'hash') }))
vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}))
vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

describe('mention-router', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('exports routeMentions function', async () => {
    const mod = await import('@/lib/mention-router')
    expect(typeof mod.routeMentions).toBe('function')
  })

  it('returns empty routing for messages without mentions', async () => {
    const { routeMentions } = await import('@/lib/mention-router')

    const mockDb = {
      prepare: vi.fn((sql: string) => {
        if (sql.includes('FROM users')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM agents')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM teams')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM messages')) return { all: vi.fn(() => []) }
        return { all: vi.fn(() => []), get: vi.fn(), run: vi.fn() }
      }),
    } as any

    const result = routeMentions(mockDb, 1, 'hello world', 'conv-1', 'user', 1)
    expect(result.routed).toHaveLength(0)
    expect(result.unresolved).toHaveLength(0)
    expect(result.humanNotified).toBe(false)
    expect(result.loopPrevented).toHaveLength(0)
  })

  it('routes @agent_name mentions', async () => {
    const { routeMentions } = await import('@/lib/mention-router')
    const { eventBus } = await import('@/lib/event-bus')

    const mockDb = {
      prepare: vi.fn((sql: string) => {
        if (sql.includes('FROM users WHERE workspace_id')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM agents') && sql.includes('workspace_id')) {
          return { all: vi.fn(() => [{ name: 'Alice', role: 'worker', config: null }]) }
        }
        if (sql.includes('FROM teams')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM messages')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM users WHERE username')) return { get: vi.fn(() => ({ id: 1 })) }
        return { all: vi.fn(() => []), get: vi.fn(), run: vi.fn() }
      }),
    } as any

    const result = routeMentions(mockDb, 42, 'hey @alice check this', 'conv-1', 'user', 1)
    expect(result.routed).toContain('Alice')
    expect(eventBus.broadcast).toHaveBeenCalledWith('chat.mention.routed', {
      messageId: 42,
      targetAgent: 'Alice',
      conversationId: 'conv-1',
    })
  })

  it('routes @human to notification', async () => {
    const { routeMentions } = await import('@/lib/mention-router')
    const { eventBus } = await import('@/lib/event-bus')
    const insertSpy = vi.fn()

    const mockDb = {
      prepare: vi.fn((sql: string) => {
        if (sql.includes('FROM users WHERE workspace_id')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM agents') && sql.includes('workspace_id')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM teams')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM messages')) return { all: vi.fn(() => []) }
        if (sql.includes('INSERT INTO notifications')) return { run: insertSpy }
        if (sql.includes('FROM users WHERE username')) return { get: vi.fn(() => ({ id: 1 })) }
        return { all: vi.fn(() => []), get: vi.fn(), run: vi.fn() }
      }),
    } as any

    const result = routeMentions(mockDb, 1, '@human please help', 'conv-1', 'user', 1)
    expect(result.humanNotified).toBe(true)
    expect(insertSpy).toHaveBeenCalled()
    expect(eventBus.broadcast).toHaveBeenCalledWith('notification.created', {})
  })

  it('reports unresolved mentions', async () => {
    const { routeMentions } = await import('@/lib/mention-router')

    const mockDb = {
      prepare: vi.fn((sql: string) => {
        if (sql.includes('FROM users WHERE workspace_id')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM agents') && sql.includes('workspace_id')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM teams')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM messages')) return { all: vi.fn(() => []) }
        return { all: vi.fn(() => []), get: vi.fn(), run: vi.fn() }
      }),
    } as any

    const result = routeMentions(mockDb, 1, 'hey @nonexistent', 'conv-1', 'user', 1)
    expect(result.unresolved).toContain('nonexistent')
    expect(result.routed).toHaveLength(0)
  })

  it('prevents loops after max agent turns', async () => {
    const { routeMentions } = await import('@/lib/mention-router')
    const { eventBus } = await import('@/lib/event-bus')

    const mockDb = {
      prepare: vi.fn((sql: string) => {
        if (sql.includes('FROM users WHERE workspace_id')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM agents') && sql.includes('workspace_id')) {
          return { all: vi.fn(() => [{ name: 'Bob', role: 'worker', config: null }]) }
        }
        if (sql.includes('FROM teams')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM messages')) {
          // 3 recent agent messages — at the limit
          return {
            all: vi.fn(() => [
              { from_agent: 'Alice' },
              { from_agent: 'Bob' },
              { from_agent: 'Charlie' },
            ]),
          }
        }
        // from_agent is an agent (not in users table)
        if (sql.includes('FROM users WHERE username')) return { get: vi.fn(() => undefined) }
        return { all: vi.fn(() => []), get: vi.fn(), run: vi.fn() }
      }),
    } as any

    const result = routeMentions(mockDb, 1, 'hey @bob do this', 'conv-1', 'AgentSender', 1)
    expect(result.loopPrevented).toContain('Bob')
    expect(result.routed).toHaveLength(0)
    expect(eventBus.broadcast).toHaveBeenCalledWith('chat.mention.loop_prevented', {
      conversationId: 'conv-1',
      agentName: 'Bob',
      turnCount: 3,
    })
  })

  it('allows routing when human message breaks agent chain', async () => {
    const { routeMentions } = await import('@/lib/mention-router')

    const mockDb = {
      prepare: vi.fn((sql: string) => {
        if (sql.includes('FROM users WHERE workspace_id')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM agents') && sql.includes('workspace_id')) {
          return { all: vi.fn(() => [{ name: 'Bob', role: 'worker', config: null }]) }
        }
        if (sql.includes('FROM teams')) return { all: vi.fn(() => []) }
        if (sql.includes('FROM messages')) {
          // Most recent is human, then agents
          return {
            all: vi.fn(() => [
              { from_agent: 'user' },  // human breaks the chain
              { from_agent: 'Alice' },
              { from_agent: 'Bob' },
            ]),
          }
        }
        if (sql.includes('FROM users WHERE username')) return { get: vi.fn(() => ({ id: 1 })) }
        return { all: vi.fn(() => []), get: vi.fn(), run: vi.fn() }
      }),
    } as any

    const result = routeMentions(mockDb, 1, 'hey @bob do this', 'conv-1', 'user', 1)
    expect(result.routed).toContain('Bob')
    expect(result.loopPrevented).toHaveLength(0)
  })

  describe('mention types', () => {
    it('MentionTarget type includes team and special', async () => {
      const mod = await import('@/lib/mentions')
      const target: import('@/lib/mentions').MentionTarget = {
        handle: 'team:dev',
        recipient: 'Dev Team',
        type: 'team',
        display: 'Dev Team',
        teamId: 1,
        memberAgents: ['Alice', 'Bob'],
      }
      expect(target.type).toBe('team')
      expect(target.memberAgents).toHaveLength(2)

      const special: import('@/lib/mentions').MentionTarget = {
        handle: 'all',
        recipient: '__all__',
        type: 'special',
        display: 'All Agents',
      }
      expect(special.type).toBe('special')
      expect(mod).toBeDefined()
    })

    it('@all expands to all agents', async () => {
      const { parseMentions } = await import('@/lib/mentions')
      const tokens = parseMentions('hello @all please respond')
      expect(tokens).toContain('all')
    })

    it('@team:name is parsed correctly', async () => {
      const { parseMentions } = await import('@/lib/mentions')
      const tokens = parseMentions('hey @team:backend check this')
      expect(tokens).toContain('team:backend')
    })
  })
})
