import { describe, it, expect, vi, beforeEach } from 'vitest'
import { z } from 'zod'

// Mock better-sqlite3
vi.mock('better-sqlite3', () => {
  const defaultStmt = {
    run: vi.fn(() => ({ lastInsertRowid: 1, changes: 1 })),
    get: vi.fn(() => ({ count: 0 })),
    all: vi.fn(() => []),
  }
  const mockPrepare = vi.fn(() => ({ ...defaultStmt }))
  const mockDb = {
    pragma: vi.fn(),
    prepare: mockPrepare,
    exec: vi.fn(),
    close: vi.fn(),
  }
  return { default: vi.fn(() => mockDb) }
})

vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))
vi.mock('@/lib/migrations', () => ({ runMigrations: vi.fn() }))
vi.mock('@/lib/phase-migrations', () => ({}))
vi.mock('@/lib/event-bus', () => ({
  eventBus: { broadcast: vi.fn(), on: vi.fn(), off: vi.fn() },
}))
vi.mock('@/lib/password', () => ({ hashPassword: vi.fn(() => 'hash') }))
vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}))
vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

// Mock scaling-engine
vi.mock('@/lib/scaling-engine', () => ({
  getScalingMetrics: vi.fn(() => ({
    queueDepth: 5,
    activeAgents: 3,
    idleAgents: 1,
    busyAgents: 2,
    busyRatio: 0.67,
  })),
  evaluateScaling: vi.fn(() => null),
  executeScaleUp: vi.fn(() => 42),
  executeScaleDown: vi.fn(),
  getGlobalAgentCap: vi.fn(() => 100),
}))

// --- Zod Schemas (replicated from routes for validation testing) ---

const createPolicySchema = z.object({
  name: z.string().min(1).max(200),
  min_agents: z.number().int().min(0).max(1000).default(0),
  max_agents: z.number().int().min(1).max(1000).default(10),
  scale_up_threshold: z.number().min(0).max(1).default(0.8),
  scale_down_threshold: z.number().min(0).max(1).default(0.2),
  cooldown_seconds: z.number().int().min(0).max(86400).default(300),
  idle_timeout_seconds: z.number().int().min(0).max(86400).default(600),
  auto_approve: z.union([z.boolean(), z.number()]).transform(v => (v ? 1 : 0)).default(0),
  agent_template: z.string().max(500).nullable().optional().default(null),
})

const updatePolicySchema = z.object({
  name: z.string().min(1).max(200).optional(),
  min_agents: z.number().int().min(0).max(1000).optional(),
  max_agents: z.number().int().min(1).max(1000).optional(),
  scale_up_threshold: z.number().min(0).max(1).optional(),
  scale_down_threshold: z.number().min(0).max(1).optional(),
  cooldown_seconds: z.number().int().min(0).max(86400).optional(),
  idle_timeout_seconds: z.number().int().min(0).max(86400).optional(),
  auto_approve: z.union([z.boolean(), z.number()]).transform(v => (v ? 1 : 0)).optional(),
  agent_template: z.string().max(500).nullable().optional(),
  enabled: z.union([z.boolean(), z.number()]).transform(v => (v ? 1 : 0)).optional(),
})

const evaluateSchema = z.object({
  policyId: z.number().int().positive(),
})

const eventActionSchema = z.object({
  action: z.enum(['approve', 'reject']),
  agentId: z.number().int().positive().optional(),
})

// --- Tests ---

describe('createPolicySchema', () => {
  it('accepts valid policy with all fields', () => {
    const result = createPolicySchema.safeParse({
      name: 'Production Autoscaler',
      min_agents: 2,
      max_agents: 20,
      scale_up_threshold: 0.8,
      scale_down_threshold: 0.3,
      cooldown_seconds: 120,
      idle_timeout_seconds: 300,
      auto_approve: true,
      agent_template: 'worker-template',
    })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.name).toBe('Production Autoscaler')
      expect(result.data.min_agents).toBe(2)
      expect(result.data.max_agents).toBe(20)
      expect(result.data.auto_approve).toBe(1)
      expect(result.data.agent_template).toBe('worker-template')
    }
  })

  it('applies defaults for optional fields', () => {
    const result = createPolicySchema.safeParse({
      name: 'Default Policy',
    })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.min_agents).toBe(0)
      expect(result.data.max_agents).toBe(10)
      expect(result.data.scale_up_threshold).toBe(0.8)
      expect(result.data.scale_down_threshold).toBe(0.2)
      expect(result.data.cooldown_seconds).toBe(300)
      expect(result.data.idle_timeout_seconds).toBe(600)
      expect(result.data.auto_approve).toBe(0)
      expect(result.data.agent_template).toBeNull()
    }
  })

  it('rejects empty name', () => {
    const result = createPolicySchema.safeParse({ name: '' })
    expect(result.success).toBe(false)
  })

  it('rejects name exceeding 200 characters', () => {
    const result = createPolicySchema.safeParse({ name: 'x'.repeat(201) })
    expect(result.success).toBe(false)
  })

  it('accepts name at exactly 200 characters', () => {
    const result = createPolicySchema.safeParse({ name: 'x'.repeat(200) })
    expect(result.success).toBe(true)
  })

  it('rejects missing name field', () => {
    const result = createPolicySchema.safeParse({})
    expect(result.success).toBe(false)
  })

  it('rejects negative min_agents', () => {
    const result = createPolicySchema.safeParse({ name: 'Test', min_agents: -1 })
    expect(result.success).toBe(false)
  })

  it('rejects max_agents of 0', () => {
    const result = createPolicySchema.safeParse({ name: 'Test', max_agents: 0 })
    expect(result.success).toBe(false)
  })

  it('rejects max_agents exceeding 1000', () => {
    const result = createPolicySchema.safeParse({ name: 'Test', max_agents: 1001 })
    expect(result.success).toBe(false)
  })

  it('rejects scale_up_threshold above 1', () => {
    const result = createPolicySchema.safeParse({ name: 'Test', scale_up_threshold: 1.1 })
    expect(result.success).toBe(false)
  })

  it('rejects scale_down_threshold below 0', () => {
    const result = createPolicySchema.safeParse({ name: 'Test', scale_down_threshold: -0.1 })
    expect(result.success).toBe(false)
  })

  it('rejects cooldown_seconds exceeding 86400', () => {
    const result = createPolicySchema.safeParse({ name: 'Test', cooldown_seconds: 86401 })
    expect(result.success).toBe(false)
  })

  it('accepts cooldown_seconds of 0', () => {
    const result = createPolicySchema.safeParse({ name: 'Test', cooldown_seconds: 0 })
    expect(result.success).toBe(true)
  })

  it('transforms boolean auto_approve to integer', () => {
    const trueResult = createPolicySchema.safeParse({ name: 'Test', auto_approve: true })
    expect(trueResult.success).toBe(true)
    if (trueResult.success) expect(trueResult.data.auto_approve).toBe(1)

    const falseResult = createPolicySchema.safeParse({ name: 'Test', auto_approve: false })
    expect(falseResult.success).toBe(true)
    if (falseResult.success) expect(falseResult.data.auto_approve).toBe(0)
  })

  it('accepts numeric auto_approve (0/1)', () => {
    const oneResult = createPolicySchema.safeParse({ name: 'Test', auto_approve: 1 })
    expect(oneResult.success).toBe(true)
    if (oneResult.success) expect(oneResult.data.auto_approve).toBe(1)

    const zeroResult = createPolicySchema.safeParse({ name: 'Test', auto_approve: 0 })
    expect(zeroResult.success).toBe(true)
    if (zeroResult.success) expect(zeroResult.data.auto_approve).toBe(0)
  })

  it('accepts null agent_template', () => {
    const result = createPolicySchema.safeParse({ name: 'Test', agent_template: null })
    expect(result.success).toBe(true)
    if (result.success) expect(result.data.agent_template).toBeNull()
  })

  it('rejects agent_template exceeding 500 characters', () => {
    const result = createPolicySchema.safeParse({ name: 'Test', agent_template: 'x'.repeat(501) })
    expect(result.success).toBe(false)
  })

  it('rejects non-integer min_agents', () => {
    const result = createPolicySchema.safeParse({ name: 'Test', min_agents: 1.5 })
    expect(result.success).toBe(false)
  })

  it('rejects non-integer max_agents', () => {
    const result = createPolicySchema.safeParse({ name: 'Test', max_agents: 5.5 })
    expect(result.success).toBe(false)
  })
})

describe('updatePolicySchema', () => {
  it('accepts partial update with name only', () => {
    const result = updatePolicySchema.safeParse({ name: 'Renamed Policy' })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.name).toBe('Renamed Policy')
      expect(result.data.min_agents).toBeUndefined()
    }
  })

  it('accepts update with multiple fields', () => {
    const result = updatePolicySchema.safeParse({
      min_agents: 5,
      max_agents: 50,
      enabled: true,
    })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.min_agents).toBe(5)
      expect(result.data.max_agents).toBe(50)
      expect(result.data.enabled).toBe(1)
    }
  })

  it('accepts empty object (no fields to update)', () => {
    const result = updatePolicySchema.safeParse({})
    expect(result.success).toBe(true)
  })

  it('transforms boolean enabled to integer', () => {
    const result = updatePolicySchema.safeParse({ enabled: false })
    expect(result.success).toBe(true)
    if (result.success) expect(result.data.enabled).toBe(0)
  })

  it('rejects empty name', () => {
    const result = updatePolicySchema.safeParse({ name: '' })
    expect(result.success).toBe(false)
  })

  it('rejects invalid scale_up_threshold', () => {
    const result = updatePolicySchema.safeParse({ scale_up_threshold: 2.0 })
    expect(result.success).toBe(false)
  })
})

describe('evaluateSchema', () => {
  it('accepts valid policyId', () => {
    const result = evaluateSchema.safeParse({ policyId: 1 })
    expect(result.success).toBe(true)
    if (result.success) expect(result.data.policyId).toBe(1)
  })

  it('rejects zero policyId', () => {
    const result = evaluateSchema.safeParse({ policyId: 0 })
    expect(result.success).toBe(false)
  })

  it('rejects negative policyId', () => {
    const result = evaluateSchema.safeParse({ policyId: -1 })
    expect(result.success).toBe(false)
  })

  it('rejects non-integer policyId', () => {
    const result = evaluateSchema.safeParse({ policyId: 1.5 })
    expect(result.success).toBe(false)
  })

  it('rejects missing policyId', () => {
    const result = evaluateSchema.safeParse({})
    expect(result.success).toBe(false)
  })

  it('rejects string policyId', () => {
    const result = evaluateSchema.safeParse({ policyId: 'abc' })
    expect(result.success).toBe(false)
  })
})

describe('eventActionSchema', () => {
  it('accepts approve action without agentId', () => {
    const result = eventActionSchema.safeParse({ action: 'approve' })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.action).toBe('approve')
      expect(result.data.agentId).toBeUndefined()
    }
  })

  it('accepts approve action with agentId', () => {
    const result = eventActionSchema.safeParse({ action: 'approve', agentId: 42 })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.action).toBe('approve')
      expect(result.data.agentId).toBe(42)
    }
  })

  it('accepts reject action', () => {
    const result = eventActionSchema.safeParse({ action: 'reject' })
    expect(result.success).toBe(true)
    if (result.success) expect(result.data.action).toBe('reject')
  })

  it('rejects invalid action', () => {
    const result = eventActionSchema.safeParse({ action: 'cancel' })
    expect(result.success).toBe(false)
  })

  it('rejects missing action', () => {
    const result = eventActionSchema.safeParse({})
    expect(result.success).toBe(false)
  })

  it('rejects non-positive agentId', () => {
    const result = eventActionSchema.safeParse({ action: 'approve', agentId: 0 })
    expect(result.success).toBe(false)
  })

  it('rejects negative agentId', () => {
    const result = eventActionSchema.safeParse({ action: 'approve', agentId: -1 })
    expect(result.success).toBe(false)
  })

  it('rejects non-integer agentId', () => {
    const result = eventActionSchema.safeParse({ action: 'approve', agentId: 1.5 })
    expect(result.success).toBe(false)
  })
})

describe('cross-field validation logic', () => {
  it('scale_down_threshold must be less than scale_up_threshold', () => {
    // This is enforced at route level, not schema level
    // Testing the logical constraint
    const valid = { down: 0.2, up: 0.8 }
    expect(valid.down).toBeLessThan(valid.up)

    const invalid = { down: 0.8, up: 0.8 }
    expect(invalid.down).toBeGreaterThanOrEqual(invalid.up)

    const inverted = { down: 0.9, up: 0.3 }
    expect(inverted.down).toBeGreaterThan(inverted.up)
  })

  it('min_agents cannot exceed max_agents', () => {
    const valid = { min: 2, max: 10 }
    expect(valid.min).toBeLessThanOrEqual(valid.max)

    const invalid = { min: 15, max: 10 }
    expect(invalid.min).toBeGreaterThan(invalid.max)
  })

  it('update merges with existing values for validation', () => {
    // Simulate: existing policy has scale_up=0.8, scale_down=0.2
    // Update sets scale_down=0.9 -> merged values: down=0.9, up=0.8 -> invalid
    const existing = { scale_up_threshold: 0.8, scale_down_threshold: 0.2 }
    const update = { scale_down_threshold: 0.9 }
    const merged = {
      scale_up: update.scale_down_threshold !== undefined ? existing.scale_up_threshold : existing.scale_up_threshold,
      scale_down: update.scale_down_threshold ?? existing.scale_down_threshold,
    }
    expect(merged.scale_down).toBeGreaterThanOrEqual(merged.scale_up)
  })
})

describe('scaling-engine mock integration', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('exports getScalingMetrics function', async () => {
    const mod = await import('@/lib/scaling-engine')
    expect(typeof mod.getScalingMetrics).toBe('function')
  })

  it('exports evaluateScaling function', async () => {
    const mod = await import('@/lib/scaling-engine')
    expect(typeof mod.evaluateScaling).toBe('function')
  })

  it('exports executeScaleUp function', async () => {
    const mod = await import('@/lib/scaling-engine')
    expect(typeof mod.executeScaleUp).toBe('function')
  })

  it('exports executeScaleDown function', async () => {
    const mod = await import('@/lib/scaling-engine')
    expect(typeof mod.executeScaleDown).toBe('function')
  })

  it('exports getGlobalAgentCap function', async () => {
    const mod = await import('@/lib/scaling-engine')
    expect(typeof mod.getGlobalAgentCap).toBe('function')
  })

  it('getScalingMetrics returns expected shape', async () => {
    const mod = await import('@/lib/scaling-engine')
    const metrics = mod.getScalingMetrics({} as Parameters<typeof mod.getScalingMetrics>[0], 1)
    expect(metrics).toHaveProperty('queueDepth')
    expect(metrics).toHaveProperty('activeAgents')
    expect(metrics).toHaveProperty('idleAgents')
    expect(metrics).toHaveProperty('busyAgents')
    expect(metrics).toHaveProperty('busyRatio')
  })

  it('evaluateScaling returns null when no action needed', async () => {
    const mod = await import('@/lib/scaling-engine')
    const result = mod.evaluateScaling({} as Parameters<typeof mod.evaluateScaling>[0], 1, 1)
    expect(result).toBeNull()
  })

  it('executeScaleUp returns new agent ID', async () => {
    const mod = await import('@/lib/scaling-engine')
    const agentId = mod.executeScaleUp({} as Parameters<typeof mod.executeScaleUp>[0], 1, 1)
    expect(agentId).toBe(42)
  })

  it('getGlobalAgentCap returns cap number', async () => {
    const mod = await import('@/lib/scaling-engine')
    expect(mod.getGlobalAgentCap()).toBe(100)
  })
})

describe('event status transitions', () => {
  it('pending events can be approved', () => {
    const validTransitions = { pending: ['approved', 'rejected'] }
    expect(validTransitions.pending).toContain('approved')
  })

  it('pending events can be rejected', () => {
    const validTransitions = { pending: ['approved', 'rejected'] }
    expect(validTransitions.pending).toContain('rejected')
  })

  it('non-pending events cannot be acted upon', () => {
    const terminalStatuses = ['approved', 'rejected', 'executed', 'failed']
    for (const status of terminalStatuses) {
      expect(status).not.toBe('pending')
    }
  })

  it('scale_down approval requires agentId', () => {
    const event = { event_type: 'scale_down', status: 'pending' }
    const action = { action: 'approve' as const, agentId: undefined }
    // Route should reject: agentId required for scale_down
    expect(event.event_type).toBe('scale_down')
    expect(action.agentId).toBeUndefined()
  })

  it('scale_up approval does not require agentId', () => {
    const event = { event_type: 'scale_up', status: 'pending' }
    const action = { action: 'approve' as const }
    expect(event.event_type).toBe('scale_up')
    expect(action).not.toHaveProperty('agentId')
  })
})

describe('auto-approve behavior', () => {
  it('auto_approve=1 triggers immediate execution after evaluation', () => {
    // When policy has auto_approve=1 and evaluateScaling returns an event,
    // the evaluate route should call executeScaleUp/Down immediately
    const policy = { auto_approve: 1 }
    expect(policy.auto_approve).toBeTruthy()
  })

  it('auto_approve=0 leaves event in pending status', () => {
    const policy = { auto_approve: 0 }
    expect(policy.auto_approve).toBeFalsy()
  })

  it('scale_down auto-approve picks oldest idle agent', () => {
    // Route queries: SELECT id FROM agents WHERE workspace_id=? AND status='idle' ORDER BY updated_at ASC LIMIT 1
    const agents = [
      { id: 10, status: 'idle', updated_at: 100 },
      { id: 11, status: 'idle', updated_at: 200 },
      { id: 12, status: 'busy', updated_at: 50 },
    ]
    const idleAgents = agents.filter(a => a.status === 'idle').sort((a, b) => a.updated_at - b.updated_at)
    expect(idleAgents[0].id).toBe(10)
  })
})

describe('query parameter validation for events', () => {
  it('valid status filters for events', () => {
    const validStatuses = ['pending', 'approved', 'rejected', 'executed', 'failed']
    for (const s of validStatuses) {
      expect(typeof s).toBe('string')
      expect(s.length).toBeGreaterThan(0)
    }
  })

  it('pagination defaults are reasonable', () => {
    const defaultLimit = 50
    const maxLimit = 200
    const defaultOffset = 0

    expect(defaultLimit).toBeLessThanOrEqual(maxLimit)
    expect(defaultOffset).toBe(0)
    expect(Math.min(parseInt('300', 10), maxLimit)).toBe(200)
    expect(Math.min(parseInt('50', 10), maxLimit)).toBe(50)
  })

  it('policy_id filter accepts positive integers', () => {
    const policyId = parseInt('5', 10)
    expect(Number.isInteger(policyId)).toBe(true)
    expect(policyId).toBeGreaterThan(0)
  })

  it('enabled filter accepts 0 or 1', () => {
    expect(parseInt('1', 10)).toBe(1)
    expect(parseInt('0', 10)).toBe(0)
  })
})

describe('workspace scoping', () => {
  it('policies are scoped to workspace_id', () => {
    const policy1 = { name: 'Autoscaler', workspace_id: 1 }
    const policy2 = { name: 'Autoscaler', workspace_id: 2 }
    // Same name in different workspaces is allowed
    expect(policy1.workspace_id).not.toBe(policy2.workspace_id)
  })

  it('events reference workspace_id for access control', () => {
    const event = { id: 1, workspace_id: 1, status: 'pending' }
    // Route checks: WHERE id = ? AND workspace_id = ?
    expect(event.workspace_id).toBe(1)
  })

  it('delete cascades events within same policy', () => {
    // DELETE FROM scaling_events WHERE policy_id = ?
    // DELETE FROM scaling_policies WHERE id = ? AND workspace_id = ?
    const policyId = 5
    const events = [
      { id: 1, policy_id: 5 },
      { id: 2, policy_id: 5 },
      { id: 3, policy_id: 6 },
    ]
    const cascaded = events.filter(e => e.policy_id === policyId)
    expect(cascaded).toHaveLength(2)
  })
})

describe('error handling patterns', () => {
  it('invalid ID returns 400', () => {
    expect(isNaN(parseInt('abc', 10))).toBe(true)
    // Route: if (isNaN(policyId)) return 400
  })

  it('not found returns 404', () => {
    // Route: if (!policy) return 404
    const policy = undefined
    expect(policy).toBeUndefined()
  })

  it('UNIQUE constraint returns 409', () => {
    const error = new Error('UNIQUE constraint failed: scaling_policies.name')
    expect(error.message).toContain('UNIQUE constraint')
  })

  it('disabled policy returns 400 for evaluation', () => {
    const policy = { enabled: 0 }
    expect(policy.enabled).toBeFalsy()
  })

  it('acting on non-pending event returns 400', () => {
    const event = { status: 'executed' }
    expect(event.status).not.toBe('pending')
  })
})
