import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'

vi.mock('better-sqlite3', () => {
  const defaultStmt = {
    run: vi.fn(() => ({ lastInsertRowid: 1, changes: 1 })),
    get: vi.fn(() => null),
    all: vi.fn(() => []),
  }
  return { default: vi.fn(() => ({ pragma: vi.fn(), prepare: vi.fn(() => ({ ...defaultStmt })), exec: vi.fn(), close: vi.fn() })) }
})

const mockDb = {
  prepare: vi.fn(() => ({
    all: vi.fn(() => []),
    get: vi.fn(),
    run: vi.fn(),
  })),
}

vi.mock('@/lib/db', () => ({
  getDatabase: vi.fn(() => mockDb),
  writeTransaction: vi.fn((_db: unknown, fn: Function) => fn(_db)),
}))

vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))
vi.mock('@/lib/migrations', () => ({ runMigrations: vi.fn() }))
vi.mock('@/lib/phase-migrations', () => ({}))
vi.mock('@/lib/password', () => ({ hashPassword: vi.fn(() => 'hash') }))
vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

const mockBroadcast = vi.fn()
const handlers: Array<(event: { type: string }) => void> = []
vi.mock('@/lib/event-bus', () => ({
  eventBus: {
    broadcast: mockBroadcast,
    on: vi.fn((event: string, handler: (e: { type: string }) => void) => {
      if (event === 'server-event') handlers.push(handler)
    }),
    off: vi.fn(),
  },
}))

vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn(), debug: vi.fn() },
}))

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const mockEvaluateScaling = vi.fn((_db?: unknown, _pId?: unknown, _ws?: unknown): unknown => null)
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const mockExecuteScaleUp = vi.fn((_db?: unknown, _eId?: unknown, _ws?: unknown): number => 99)
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const mockExecuteScaleDown = vi.fn((_db?: unknown, _eId?: unknown, _aId?: unknown, _ws?: unknown) => {})

vi.mock('@/lib/scaling-engine', () => ({
  evaluateScaling: vi.fn((_db: unknown, _policyId: unknown, _wsId: unknown) =>
    mockEvaluateScaling(_db, _policyId, _wsId)),
  executeScaleUp: vi.fn((_db: unknown, _eventId: unknown, _wsId: unknown) =>
    mockExecuteScaleUp(_db, _eventId, _wsId)),
  executeScaleDown: vi.fn((_db: unknown, _eventId: unknown, _agentId: unknown, _wsId: unknown) =>
    mockExecuteScaleDown(_db, _eventId, _agentId, _wsId)),
}))

describe('scaling-triggers', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    handlers.length = 0
  })

  afterEach(async () => {
    const { resetScalingTriggers } = await import('@/lib/scaling-triggers')
    resetScalingTriggers()
  })

  it('registers event handlers on init', async () => {
    const { initScalingTriggers } = await import('@/lib/scaling-triggers')
    initScalingTriggers()
    expect(handlers.length).toBeGreaterThan(0)
  })

  it('is idempotent — safe to call multiple times', async () => {
    const { initScalingTriggers } = await import('@/lib/scaling-triggers')
    initScalingTriggers()
    initScalingTriggers()
    initScalingTriggers()
    expect(handlers.length).toBe(1)
  })

  it('evaluates auto-approve policies on task.created', async () => {
    const { initScalingTriggers } = await import('@/lib/scaling-triggers')
    initScalingTriggers()

    // Set up policy mock
    mockDb.prepare.mockReturnValueOnce({
      all: vi.fn(() => [{ id: 1, workspace_id: 1 }]),
      get: vi.fn(),
      run: vi.fn(),
    })

    // Simulate task.created event
    handlers[0]({ type: 'task.created' })

    expect(mockEvaluateScaling).toHaveBeenCalledWith(mockDb, 1, 1)
  })

  it('executes scale-up when evaluation returns scale_up event', async () => {
    const { initScalingTriggers } = await import('@/lib/scaling-triggers')
    initScalingTriggers()

    mockDb.prepare.mockReturnValueOnce({
      all: vi.fn(() => [{ id: 1, workspace_id: 1 }]),
      get: vi.fn(),
      run: vi.fn(),
    })

    mockEvaluateScaling.mockReturnValueOnce({
      id: 10,
      event_type: 'scale_up',
      agent_id: null,
      status: 'pending',
    })

    handlers[0]({ type: 'task.created' })

    expect(mockExecuteScaleUp).toHaveBeenCalledWith(mockDb, 10, 1)
  })

  it('executes scale-down when evaluation returns scale_down with agent_id', async () => {
    const { initScalingTriggers } = await import('@/lib/scaling-triggers')
    initScalingTriggers()

    mockDb.prepare.mockReturnValueOnce({
      all: vi.fn(() => [{ id: 2, workspace_id: 1 }]),
      get: vi.fn(),
      run: vi.fn(),
    })

    mockEvaluateScaling.mockReturnValueOnce({
      id: 20,
      event_type: 'scale_down',
      agent_id: 5,
      status: 'pending',
    })

    handlers[0]({ type: 'task.status_changed' })

    expect(mockExecuteScaleDown).toHaveBeenCalledWith(mockDb, 20, 5, 1)
  })

  it('debounces rapid events', async () => {
    const { initScalingTriggers } = await import('@/lib/scaling-triggers')
    initScalingTriggers()

    mockDb.prepare.mockReturnValue({
      all: vi.fn(() => []),
      get: vi.fn(),
      run: vi.fn(),
    })

    // Fire 3 rapid events
    handlers[0]({ type: 'task.created' })
    handlers[0]({ type: 'task.created' })
    handlers[0]({ type: 'task.created' })

    // Only 1 evaluation (the rest are within cooldown)
    expect(mockDb.prepare).toHaveBeenCalledTimes(1)
  })

  it('ignores non-task events', async () => {
    const { initScalingTriggers } = await import('@/lib/scaling-triggers')
    initScalingTriggers()

    handlers[0]({ type: 'agent.updated' })
    handlers[0]({ type: 'chat.message' })

    expect(mockEvaluateScaling).not.toHaveBeenCalled()
  })
})
