import { describe, it, expect, vi, beforeEach } from 'vitest'

// Mock better-sqlite3
vi.mock('better-sqlite3', () => {
  const defaultStmt = {
    run: vi.fn(() => ({ lastInsertRowid: 1, changes: 1 })),
    get: vi.fn(() => ({ count: 0 })),
    all: vi.fn(() => []),
  }
  const mockPrepare = vi.fn(() => ({ ...defaultStmt }))
  const mockDb = {
    pragma: vi.fn(),
    prepare: mockPrepare,
    exec: vi.fn(),
    close: vi.fn(),
  }
  return { default: vi.fn(() => mockDb) }
})

vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))
vi.mock('@/lib/migrations', () => ({ runMigrations: vi.fn() }))
vi.mock('@/lib/phase-migrations', () => ({}))
vi.mock('@/lib/event-bus', () => ({
  eventBus: { broadcast: vi.fn(), on: vi.fn(), off: vi.fn() },
}))
vi.mock('@/lib/password', () => ({ hashPassword: vi.fn(() => 'hash') }))
vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}))
vi.mock('@/lib/mentions', () => ({ parseMentions: vi.fn(() => []) }))
vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

describe('Spatial API validation', () => {
  let getDatabase: typeof import('@/lib/db').getDatabase

  beforeEach(async () => {
    vi.resetModules()
    const mod = await import('@/lib/db')
    getDatabase = mod.getDatabase
  })

  it('relationship type constraint rejects invalid types', () => {
    const validTypes = ['delegation', 'communication', 'supervision']
    const invalidTypes = ['friendship', 'parent', '', 'DELEGATION']

    for (const t of validTypes) {
      expect(validTypes.includes(t)).toBe(true)
    }
    for (const t of invalidTypes) {
      expect(validTypes.includes(t)).toBe(false)
    }
  })

  it('self-relationship is rejected', () => {
    const sourceId = 1
    const targetId = 1
    expect(sourceId === targetId).toBe(true)
  })

  it('positions array requires numeric fields', () => {
    const valid = { agent_id: 1, x: 100.5, y: 200.3 }
    const invalid = { agent_id: 'abc', x: 100, y: 200 }

    expect(typeof valid.agent_id).toBe('number')
    expect(typeof valid.x).toBe('number')
    expect(typeof valid.y).toBe('number')
    expect(typeof invalid.agent_id).toBe('string')
  })

  it('database module exports writeTransaction', async () => {
    const mod = await import('@/lib/db')
    expect(typeof mod.writeTransaction).toBe('function')
  })

  it('EventDataMap includes spatial edge events', async () => {
    // Type-level check — if this compiles, the events exist
    const { eventBus } = await import('@/lib/event-bus')
    expect(typeof eventBus.broadcast).toBe('function')
  })
})
