import { describe, it, expect, vi, beforeEach } from 'vitest'

// Mock better-sqlite3
vi.mock('better-sqlite3', () => {
  const defaultStmt = {
    run: vi.fn(() => ({ lastInsertRowid: 1, changes: 1 })),
    get: vi.fn(() => ({ count: 0 })),
    all: vi.fn(() => []),
  }
  const mockPrepare = vi.fn(() => ({ ...defaultStmt }))
  const mockDb = {
    pragma: vi.fn(),
    prepare: mockPrepare,
    exec: vi.fn(),
    close: vi.fn(),
  }
  return { default: vi.fn(() => mockDb) }
})

vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))
vi.mock('@/lib/migrations', () => ({ runMigrations: vi.fn() }))
vi.mock('@/lib/phase-migrations', () => ({}))
vi.mock('@/lib/event-bus', () => ({
  eventBus: { broadcast: vi.fn(), on: vi.fn(), off: vi.fn() },
}))
vi.mock('@/lib/password', () => ({ hashPassword: vi.fn(() => 'hash') }))
vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}))
vi.mock('@/lib/mentions', () => ({ parseMentions: vi.fn(() => []) }))
vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

// Mock writeTransaction to just call the callback
vi.mock('@/lib/db', async (importOriginal) => {
  const orig = await importOriginal<typeof import('@/lib/db')>()
  return {
    ...orig,
    writeTransaction: vi.fn((_db: unknown, fn: (db: unknown) => unknown) => fn(_db)),
    getDatabase: orig.getDatabase,
  }
})

describe('workflow-engine', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  describe('module exports', () => {
    it('exports all 6 functions', async () => {
      const mod = await import('@/lib/workflow-engine')
      expect(typeof mod.createWorkflowRun).toBe('function')
      expect(typeof mod.completePhase).toBe('function')
      expect(typeof mod.advanceWorkflow).toBe('function')
      expect(typeof mod.approvePhase).toBe('function')
      expect(typeof mod.rejectPhase).toBe('function')
      expect(typeof mod.getWorkflowRunStatus).toBe('function')
    })

    it('exports type interfaces (compile check)', async () => {
      const mod = await import('@/lib/workflow-engine')
      // Type-level check — WorkflowPhaseRow, WorkflowRunRow, WorkflowPhaseRunRow
      const phaseRow: import('@/lib/workflow-engine').WorkflowPhaseRow = {
        id: 1, template_id: 1, name: 'test', phase_order: 1,
        agent_role: null, input_schema: null, output_schema: null,
        requires_approval: 0, description: null,
      }
      const runRow: import('@/lib/workflow-engine').WorkflowRunRow = {
        id: 1, template_id: 1, status: 'running', current_phase_id: 1,
        input_data: null, started_at: null, completed_at: null,
        workspace_id: 1, created_by: 'test', created_at: 0, updated_at: 0,
      }
      const phaseRunRow: import('@/lib/workflow-engine').WorkflowPhaseRunRow = {
        id: 1, run_id: 1, phase_id: 1, status: 'pending',
        input_artifact: null, output_artifact: null, validation_error: null,
        approved_by: null, approved_at: null, started_at: null, completed_at: null,
      }
      expect(phaseRow.id).toBe(1)
      expect(runRow.status).toBe('running')
      expect(phaseRunRow.status).toBe('pending')
      // Ensures mod is used
      expect(mod).toBeDefined()
    })
  })

  describe('createWorkflowRun', () => {
    it('throws when template not found', async () => {
      const { createWorkflowRun } = await import('@/lib/workflow-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => undefined),
          all: vi.fn(() => []),
          run: vi.fn(() => ({ lastInsertRowid: 1, changes: 1 })),
        })),
      } as any

      expect(() => createWorkflowRun(mockDb, 999, null, 'user', 1)).toThrow('Template 999 not found')
    })

    it('throws when template has no phases', async () => {
      const { createWorkflowRun } = await import('@/lib/workflow-engine')
      let callCount = 0
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => {
            callCount++
            return callCount === 1 ? { id: 1, name: 'Test' } : undefined
          }),
          all: vi.fn(() => []),
          run: vi.fn(() => ({ lastInsertRowid: 1, changes: 1 })),
        })),
      } as any

      expect(() => createWorkflowRun(mockDb, 1, null, 'user', 1)).toThrow('has no phases')
    })

    it('creates run and phase runs for valid template', async () => {
      const { createWorkflowRun } = await import('@/lib/workflow-engine')
      const { eventBus } = await import('@/lib/event-bus')

      const phases = [
        { id: 10, template_id: 1, name: 'Phase 1', phase_order: 1 },
        { id: 11, template_id: 1, name: 'Phase 2', phase_order: 2 },
      ]

      const runStmt = vi.fn(() => ({ lastInsertRowid: BigInt(42), changes: 1 }))
      const insertPhaseRunStmt = vi.fn()
      let prepareCallCount = 0

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          prepareCallCount++
          if (sql.includes('SELECT id, name FROM workflow_templates')) {
            return { get: vi.fn(() => ({ id: 1, name: 'Test Template' })) }
          }
          if (sql.includes('SELECT * FROM workflow_phases WHERE template_id')) {
            return { all: vi.fn(() => phases) }
          }
          if (sql.includes('INSERT INTO workflow_runs')) {
            return { run: runStmt }
          }
          if (sql.includes('INSERT INTO workflow_phase_runs')) {
            return { run: insertPhaseRunStmt }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = createWorkflowRun(mockDb, 1, '{"input":"data"}', 'admin', 1)
      expect(result.runId).toBe(42)
      expect(runStmt).toHaveBeenCalledOnce()
      // First phase is running, second is pending
      expect(insertPhaseRunStmt).toHaveBeenCalledTimes(2)
      expect(insertPhaseRunStmt).toHaveBeenCalledWith(42, 10, 'running', '{"input":"data"}', expect.any(Number))
      expect(insertPhaseRunStmt).toHaveBeenCalledWith(42, 11, 'pending', null, null)
      expect(eventBus.broadcast).toHaveBeenCalledWith('workflow.run.started', {
        runId: 42,
        workflowId: 1,
        templateName: 'Test Template',
      })
    })
  })

  describe('completePhase', () => {
    it('throws when phase run not found', async () => {
      const { completePhase } = await import('@/lib/workflow-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => undefined),
          run: vi.fn(),
        })),
      } as any

      expect(() => completePhase(mockDb, 1, 999, '{}')).toThrow('Phase run not found')
    })

    it('throws when phase is not running', async () => {
      const { completePhase } = await import('@/lib/workflow-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => ({ id: 1, run_id: 1, phase_id: 1, status: 'pending' })),
          run: vi.fn(),
        })),
      } as any

      expect(() => completePhase(mockDb, 1, 1, '{}')).toThrow('Phase is pending, expected running')
    })

    it('returns validation_error for missing required field', async () => {
      const { completePhase } = await import('@/lib/workflow-engine')
      const updateStmt = vi.fn()
      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM workflow_phase_runs')) {
            return { get: vi.fn(() => ({ id: 1, run_id: 1, phase_id: 10, status: 'running' })) }
          }
          if (sql.includes('SELECT * FROM workflow_phases')) {
            return {
              get: vi.fn(() => ({
                id: 10, output_schema: JSON.stringify({ required: ['title', 'body'] }),
              })),
            }
          }
          return { run: updateStmt, get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = completePhase(mockDb, 1, 1, JSON.stringify({ title: 'hi' }))
      expect(result.status).toBe('validation_error')
      expect(result.validationError).toContain('Missing required field: body')
    })

    it('returns validation_error for invalid JSON output', async () => {
      const { completePhase } = await import('@/lib/workflow-engine')
      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM workflow_phase_runs')) {
            return { get: vi.fn(() => ({ id: 1, run_id: 1, phase_id: 10, status: 'running' })) }
          }
          if (sql.includes('SELECT * FROM workflow_phases')) {
            return {
              get: vi.fn(() => ({
                id: 10, output_schema: JSON.stringify({ required: ['x'] }),
              })),
            }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = completePhase(mockDb, 1, 1, 'not-json')
      expect(result.status).toBe('validation_error')
    })

    it('completes phase with valid output', async () => {
      const { completePhase } = await import('@/lib/workflow-engine')
      const updateStmt = vi.fn()
      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM workflow_phase_runs')) {
            return { get: vi.fn(() => ({ id: 1, run_id: 1, phase_id: 10, status: 'running' })) }
          }
          if (sql.includes('SELECT * FROM workflow_phases')) {
            return { get: vi.fn(() => ({ id: 10, output_schema: null })) }
          }
          if (sql.includes('UPDATE workflow_phase_runs')) {
            return { run: updateStmt }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = completePhase(mockDb, 1, 1, '{"done":true}')
      expect(result.status).toBe('completed')
      expect(updateStmt).toHaveBeenCalledWith('{"done":true}', 1)
    })
  })

  describe('advanceWorkflow', () => {
    it('throws when run not found', async () => {
      const { advanceWorkflow } = await import('@/lib/workflow-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => undefined),
          all: vi.fn(() => []),
          run: vi.fn(),
        })),
      } as any

      expect(() => advanceWorkflow(mockDb, 999)).toThrow('Run not found')
    })

    it('completes workflow when no next phase', async () => {
      const { advanceWorkflow } = await import('@/lib/workflow-engine')
      const { eventBus } = await import('@/lib/event-bus')
      const updateStmt = vi.fn()

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM workflow_runs WHERE id')) {
            return {
              get: vi.fn(() => ({
                id: 1, template_id: 1, status: 'running', current_phase_id: 10,
              })),
            }
          }
          if (sql.includes('SELECT * FROM workflow_phases WHERE template_id')) {
            return {
              all: vi.fn(() => [
                { id: 10, template_id: 1, name: 'Phase 1', phase_order: 1, requires_approval: 0 },
              ]),
            }
          }
          if (sql.includes('SELECT * FROM workflow_phase_runs WHERE run_id')) {
            return {
              all: vi.fn(() => [
                { id: 100, run_id: 1, phase_id: 10, status: 'completed', output_artifact: '{}' },
              ]),
            }
          }
          return { run: updateStmt, get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = advanceWorkflow(mockDb, 1)
      expect(result.status).toBe('completed')
      expect(eventBus.broadcast).toHaveBeenCalledWith('workflow.run.completed', { runId: 1, status: 'completed' })
    })

    it('pauses at approval gate', async () => {
      const { advanceWorkflow } = await import('@/lib/workflow-engine')
      const { eventBus } = await import('@/lib/event-bus')

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM workflow_runs WHERE id')) {
            return {
              get: vi.fn(() => ({
                id: 1, template_id: 1, status: 'running', current_phase_id: 10,
              })),
            }
          }
          if (sql.includes('SELECT * FROM workflow_phases WHERE template_id')) {
            return {
              all: vi.fn(() => [
                { id: 10, template_id: 1, name: 'Phase 1', phase_order: 1, requires_approval: 0 },
                { id: 11, template_id: 1, name: 'Phase 2', phase_order: 2, requires_approval: 1 },
              ]),
            }
          }
          if (sql.includes('SELECT * FROM workflow_phase_runs WHERE run_id')) {
            return {
              all: vi.fn(() => [
                { id: 100, run_id: 1, phase_id: 10, status: 'completed', output_artifact: '{"result":"ok"}' },
                { id: 101, run_id: 1, phase_id: 11, status: 'pending' },
              ]),
            }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = advanceWorkflow(mockDb, 1)
      expect(result.status).toBe('paused')
      expect(result.nextPhase).toEqual({ id: 11, name: 'Phase 2', requiresApproval: true })
      expect(eventBus.broadcast).toHaveBeenCalledWith('workflow.phase.approval_required', {
        runId: 1, phaseId: 11, phaseName: 'Phase 2',
      })
    })

    it('advances to next running phase', async () => {
      const { advanceWorkflow } = await import('@/lib/workflow-engine')
      const { eventBus } = await import('@/lib/event-bus')

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM workflow_runs WHERE id')) {
            return {
              get: vi.fn(() => ({
                id: 1, template_id: 1, status: 'running', current_phase_id: 10,
              })),
            }
          }
          if (sql.includes('SELECT * FROM workflow_phases WHERE template_id')) {
            return {
              all: vi.fn(() => [
                { id: 10, template_id: 1, name: 'Phase 1', phase_order: 1, requires_approval: 0 },
                { id: 11, template_id: 1, name: 'Phase 2', phase_order: 2, requires_approval: 0 },
              ]),
            }
          }
          if (sql.includes('SELECT * FROM workflow_phase_runs WHERE run_id')) {
            return {
              all: vi.fn(() => [
                { id: 100, run_id: 1, phase_id: 10, status: 'completed', output_artifact: '{"x":1}' },
                { id: 101, run_id: 1, phase_id: 11, status: 'pending' },
              ]),
            }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = advanceWorkflow(mockDb, 1)
      expect(result.status).toBe('running')
      expect(result.nextPhase).toEqual({ id: 11, name: 'Phase 2', requiresApproval: false })
      expect(eventBus.broadcast).toHaveBeenCalledWith('workflow.phase.transition', {
        runId: 1, fromPhase: 'Phase 1', toPhase: 'Phase 2',
      })
    })
  })

  describe('approvePhase', () => {
    it('throws when phase not paused', async () => {
      const { approvePhase } = await import('@/lib/workflow-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => ({ id: 1, run_id: 1, phase_id: 10, status: 'running' })),
          run: vi.fn(),
        })),
      } as any

      expect(() => approvePhase(mockDb, 1, 1, 'admin')).toThrow('Phase is running, expected paused')
    })

    it('approves paused phase and resumes run', async () => {
      const { approvePhase } = await import('@/lib/workflow-engine')
      const updatePhaseStmt = vi.fn()
      const updateRunStmt = vi.fn()
      let updateCalls = 0

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM workflow_phase_runs')) {
            return { get: vi.fn(() => ({ id: 1, run_id: 1, phase_id: 10, status: 'paused' })) }
          }
          if (sql.includes('UPDATE workflow_phase_runs')) {
            return { run: updatePhaseStmt }
          }
          if (sql.includes('UPDATE workflow_runs')) {
            return { run: updateRunStmt }
          }
          if (sql.includes('SELECT name FROM workflow_phases')) {
            return { get: vi.fn(() => ({ name: 'Review Phase' })) }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = approvePhase(mockDb, 1, 1, 'admin-user')
      expect(result.status).toBe('running')
      expect(updatePhaseStmt).toHaveBeenCalledWith('admin-user', 1)
      expect(updateRunStmt).toHaveBeenCalledWith(1)
    })
  })

  describe('rejectPhase', () => {
    it('throws when phase not paused', async () => {
      const { rejectPhase } = await import('@/lib/workflow-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => ({ id: 1, run_id: 1, phase_id: 10, status: 'completed' })),
          run: vi.fn(),
        })),
      } as any

      expect(() => rejectPhase(mockDb, 1, 1, 'bad output')).toThrow('Phase is completed, expected paused')
    })

    it('rejects phase and fails run', async () => {
      const { rejectPhase } = await import('@/lib/workflow-engine')
      const { eventBus } = await import('@/lib/event-bus')

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM workflow_phase_runs')) {
            return { get: vi.fn(() => ({ id: 1, run_id: 1, phase_id: 10, status: 'paused' })) }
          }
          return { run: vi.fn(), get: vi.fn(), all: vi.fn(() => []) }
        }),
      } as any

      const result = rejectPhase(mockDb, 1, 1, 'Does not meet criteria')
      expect(result.status).toBe('failed')
      expect(eventBus.broadcast).toHaveBeenCalledWith('workflow.run.completed', { runId: 1, status: 'failed' })
    })
  })

  describe('getWorkflowRunStatus', () => {
    it('returns null when run not found', async () => {
      const { getWorkflowRunStatus } = await import('@/lib/workflow-engine')
      const mockDb = {
        prepare: vi.fn(() => ({
          get: vi.fn(() => undefined),
          all: vi.fn(() => []),
        })),
      } as any

      const result = getWorkflowRunStatus(mockDb, 999)
      expect(result).toBeNull()
    })

    it('returns run with phases', async () => {
      const { getWorkflowRunStatus } = await import('@/lib/workflow-engine')
      const run = { id: 1, template_id: 1, status: 'running', current_phase_id: 10 }
      const phases = [
        { id: 100, run_id: 1, phase_id: 10, status: 'completed', phase_name: 'Build', phase_order: 1 },
        { id: 101, run_id: 1, phase_id: 11, status: 'running', phase_name: 'Test', phase_order: 2 },
      ]

      const mockDb = {
        prepare: vi.fn((sql: string) => {
          if (sql.includes('SELECT * FROM workflow_runs WHERE id')) {
            return { get: vi.fn(() => run) }
          }
          return { all: vi.fn(() => phases), get: vi.fn() }
        }),
      } as any

      const result = getWorkflowRunStatus(mockDb, 1)
      expect(result).not.toBeNull()
      expect(result!.run).toEqual(run)
      expect(result!.phases).toHaveLength(2)
      expect(result!.phases[0].phase_name).toBe('Build')
      expect(result!.phases[1].phase_name).toBe('Test')
    })
  })

  describe('workflow status values', () => {
    it('run statuses are valid', () => {
      const validStatuses = ['pending', 'running', 'paused', 'completed', 'failed']
      for (const s of validStatuses) {
        expect(validStatuses).toContain(s)
      }
    })

    it('phase run statuses include rejected', () => {
      const validStatuses = ['pending', 'running', 'paused', 'completed', 'failed', 'rejected']
      expect(validStatuses).toContain('rejected')
      expect(validStatuses).toHaveLength(6)
    })
  })
})
