import { describe, it, expect, vi, beforeEach } from 'vitest'

// Mock better-sqlite3 before importing db module
vi.mock('better-sqlite3', () => {
  const defaultStmt = {
    run: vi.fn(),
    get: vi.fn(() => ({ count: 0 })),
    all: vi.fn(() => []),
  }
  const mockPrepare = vi.fn(() => ({ ...defaultStmt }))
  const mockPragma = vi.fn()
  const mockExec = vi.fn()
  const mockDb = {
    pragma: mockPragma,
    prepare: mockPrepare,
    exec: mockExec,
    close: vi.fn(),
  }
  return {
    default: vi.fn(() => mockDb),
  }
})

// Mock dependencies that db.ts imports
vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))
vi.mock('@/lib/migrations', () => ({ runMigrations: vi.fn() }))
vi.mock('@/lib/phase-migrations', () => ({}))
vi.mock('@/lib/event-bus', () => ({
  eventBus: { broadcast: vi.fn(), on: vi.fn(), off: vi.fn() },
}))
vi.mock('@/lib/password', () => ({ hashPassword: vi.fn(() => 'hash') }))
vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}))
vi.mock('@/lib/mentions', () => ({ parseMentions: vi.fn(() => []) }))
vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

function defaultStmt() {
  return { run: vi.fn(), get: vi.fn(() => ({ count: 0 })), all: vi.fn(() => []) } as any
}

describe('writeTransaction', () => {
  let writeTransaction: typeof import('@/lib/db').writeTransaction
  let getDatabase: typeof import('@/lib/db').getDatabase

  beforeEach(async () => {
    vi.resetModules()
    const mod = await import('@/lib/db')
    writeTransaction = mod.writeTransaction
    getDatabase = mod.getDatabase
  })

  it('commits on successful execution', () => {
    const db = getDatabase()

    const beginRun = vi.fn()
    const commitRun = vi.fn()
    const rollbackRun = vi.fn()

    vi.mocked(db.prepare).mockImplementation((sql: string) => {
      if (sql === 'BEGIN IMMEDIATE') return { run: beginRun } as any
      if (sql === 'COMMIT') return { run: commitRun } as any
      if (sql === 'ROLLBACK') return { run: rollbackRun } as any
      return defaultStmt()
    })

    const result = writeTransaction(db, () => 'success')

    expect(result).toBe('success')
    expect(beginRun).toHaveBeenCalled()
    expect(commitRun).toHaveBeenCalled()
    expect(rollbackRun).not.toHaveBeenCalled()
  })

  it('rolls back on error and re-throws', () => {
    const db = getDatabase()

    const beginRun = vi.fn()
    const commitRun = vi.fn()
    const rollbackRun = vi.fn()

    vi.mocked(db.prepare).mockImplementation((sql: string) => {
      if (sql === 'BEGIN IMMEDIATE') return { run: beginRun } as any
      if (sql === 'COMMIT') return { run: commitRun } as any
      if (sql === 'ROLLBACK') return { run: rollbackRun } as any
      return defaultStmt()
    })

    expect(() => {
      writeTransaction(db, () => {
        throw new Error('Write failed')
      })
    }).toThrow('Write failed')

    expect(beginRun).toHaveBeenCalled()
    expect(rollbackRun).toHaveBeenCalled()
    expect(commitRun).not.toHaveBeenCalled()
  })

  it('returns the value from the transaction function', () => {
    const db = getDatabase()

    vi.mocked(db.prepare).mockImplementation(() => defaultStmt())

    const result = writeTransaction(db, () => ({ inserted: 42 }))

    expect(result).toEqual({ inserted: 42 })
  })
})
